# Python Basics


### 1.1 Dəyişənlər və Operatorlar

## Əsas dəyişən tipləri

**Python-da tip, dəyişənin içində hansı növ məlumatın olduğunu göstərir. Məsələn, ədəd, mətn və ya siyahı kimi.**

**`tam_ədəd`** dəyişəni **tam ədəd (int)** tipindədir və qiyməti 42-dir.  
**`kəsr_ədəd`** dəyişəni **ondalıklı ədəd (float)** tipindədir və qiyməti 3.14-dür.  
**`mətn`** dəyişəni **mətin (string)** tipindədir və "Salam, Dünya!" məzmununa malikdir.  
**`məntiqi`** dəyişəni **bool (məntiqi)** tipindədir və qiyməti True-dur.  
**`heç_nə`** dəyişəni **NoneType** tipindədir və heç bir dəyər daşımır (boşdur).  


In [4]:
tam_ədəd = 42                  # int
kəsr_ədəd = 3.14               # float
mətn = "Salam, Dünya!"         # str
məntiqi = True                 # bool
heç_nə = None                  # NoneType

### Çoxsətirli mətn

**`çoxsətirli`** dəyişəni üçqat qoşa dırnaq `""" """` içində yazılmış,  
yəni **çoxsətirli mətn (string)** tipindədir.  
Bu üsulla mətn bir neçə sətirdə yazıla bilər.  

In [5]:
çoxsətirli = """
Bu çoxsətirli
mətn nümunəsidir.
"""

In [7]:
print(çoxsətirli)


Bu çoxsətirli
mətn nümunəsidir.



In [8]:
çoxsətirli

'\nBu çoxsətirli\nmətn nümunəsidir.\n'

## Dinamik tip dəyişmə

`dəyişən` əvvəlcə **tam ədəd (int)** tipində təyin olunur və qiyməti 10-dur.  
`print(type(dəyişən))` ilə dəyişənin tipi ekrana çıxarılır və `<class 'int'>` göstərilir.  
Sonra `dəyişən` **mətin (str)** tipinə dəyişdirilir və "on" dəyəri verilir.  
Yenidən `print(type(dəyişən))` işlədilərək tip yoxlanılır və `<class 'str'>` çıxır.  
Python-da dəyişənin tipi istənilən vaxt dəyişə bilər, yəni dəyişkəndir (dynamic typing).  


In [10]:
dəyişən = 10
print(type(dəyişən))  # <class 'int'>
dəyişən = "on"
print(type(dəyişən))  # <class 'str'>


<class 'int'>
<class 'str'>


## Operatorlara nümunələr

`a` və `b` dəyişənlərinə müvafiq olaraq 10 və 3 qiymətləri verilir.  
**Toplama (`+`)** əməliyyatı `a + b` ilə 13 nəticəsini verir.  
**Çıxma (`-`)**, **vurma (`*`)**, **bölmə (`/`)** kimi əsas riyazi əməliyyatlar göstərilir.  
**Tam bölmə (`//`)** `a`-nın `b`-yə bölünməsinin tam hissəsini qaytarır.  
**Qalıq (`%`)** əməliyyatı bölmədən qalanı tapır.  
**Üst (`**`)** əməliyyatı `a`-nın `b`-ci qüvvətini hesablamaq üçündür (10^3 = 1000).  


In [5]:
a, b = 10, 3

print("Toplama:", a + b)       # 13
print("Çıxma:", a - b)         # 7
print("Vurma:", a * b)         # 30
print("Bölmə:", a / b)         # 3.333...
print("Tam bölmə:", a // b)    # 3
print("Qalıq:", a % b)         # 1
print("Üst:", a ** b)          # 1000


Toplama: 13
Çıxma: 7
Vurma: 30
Bölmə: 3.3333333333333335
Tam bölmə: 3
Qalıq: 1
Üst: 1000


## Müqayisə operatorları

Bu müqayisə operatorları iki dəyəri bir-biri ilə müqayisə edir:

- `a > b` → `True` (10 > 3)
- `a < b` → `False` (10 < 3 deyil)
- `a == b` → `False` (10 bərabər deyil 3-ə)
- `a != b` → `True` (10 fərqlidir 3-dən)

Bu cür operatorlar **şərtlərin yoxlanması** və **idarəetmə strukturlarında** geniş istifadə olunur.


In [7]:
print("a > b:", a > b)         # True
print("a == b:", a == b)       # False
print("a != b:", a != b)       # True

a > b: True
a == b: False
a != b: True


## Məntiqi operatorlar

`True` və `False` məntiqi dəyərləri ilə **AND**, **OR** və **NOT** əməliyyatları tətbiq olunur.  
**AND (`and`)** yalnız hər iki tərəf `True` olduqda `True` qaytarır.  
**OR (`or`)** tərəflərdən ən az biri `True` olduqda `True` nəticəsi verir.  
**NOT (`not`)** isə məntiqi dəyərin tərsini verir (məsələn, `not True` → `False`).


In [13]:
print("AND:", True and False)  # False
print("OR:", True or False)    # True
print("NOT:", not True)        # False

AND: False
OR: True
NOT: False


# 1.2 Şərt İfadələri

 Şərt İfadələri proqramlaşdırmada müxtəlif vəziyyətlərə görə fərqli əməliyyatların icra olunmasını təmin edən məntiqi yoxlamalardır.

`bal` dəyişəni 85 olaraq təyin edilir.  
**`if`**, **`elif`** və **`else`** şərt blokları ilə qiymətə görə fərqli mesajlar göstərilir.  
**`:`** işarəsindən sonra indentasiya (4 boşluq və ya tab) mütləqdir.  
Bal 90 və yuxarıdırsa "Əla!", 70-89 arası "Yaxşı!", 50-69 arası "Qənaətbəxş",  
50-dən aşağı olduqda isə "Kəsildiniz" mesajı çıxır.  
```


In [15]:
bal = 85
#burda her zaman indentention gozlenmelidir yeni : den sonra asagi setirde bir tab ve ya 4 bosluq
if bal >= 90:
    print("Əla!")
elif bal >= 70:
    print("Yaxşı!")
elif bal >= 50:
    print("Qənaətbəxş")
else:
    print("Kəsildiniz")

Yaxşı!


yas dəyişəni istifadəçidən tam ədəd kimi alınır.  
Vətəndaşlıq və ali təhsil məlumatları "bəli/xeyr" formatında daxil edilir.  
**`if`**, **`elif`** və **`else`** blokları ilə müraciət üçün uyğunluq yoxlanılır.  
Əgər şəxs ya vətəndaşdır, ya da ali təhsillidir və yaşı 18-dən yuxarıdırsa, müraciət edə bilər.  
Əks halda uyğun deyilsə, ya da bəzi hallarda sənədlə müraciət mümkündür.  


In [ ]:
yas = int(input("Zəhmət olmasa yaşınızı daxil edin: "))
vatandasliq = input("Azərbaycan vətəndaşısınız? (bəli/xeyr): ").lower()
ali_tehsil = input("Ali təhsilli şəxssiniz? (bəli/xeyr): ").lower()

# Şərt: (vətəndaşdır VƏ YA ali təhsillidir) VƏ yaş >= 18
if (vatandasliq == "bəli" or ali_tehsil == "bəli") and yas >= 18:
    print("Siz ilkin olaraq müraciət edə bilərsiniz.")

# Əgər şəxs nə vətəndaşdır, nə də ali təhsillidir, və yaşı da 18-dən kiçikdirsə
elif not (vatandasliq == "bəli" or ali_tehsil == "bəli") or yas < 18:
    print("Təəssüf, siz müraciət şərtlərinə uyğun deyilsiniz.")

# Digər hallarda
else:
    print("Əlavə sənədlərlə müraciət etmək mümkündür.")


### İç-içə şərtlər

### İç-içə şərtlər (nested conditions) biri digərinin içində yerləşən şərt bloklarıdır və mürəkkəb məntiqi qərarları mərhələli şəkildə yoxlamağa imkan verir.

In [3]:
yaş = 20
təhsil = "ali"

if yaş >= 18:
    if təhsil == "ali":
        print("İş üçün uyğunsunuz")
    else:
        print("Təhsil şərtinə uyğun deyilsiniz")
else:
    print("Yaş şərtinə uyğun deyilsiniz")

İş üçün uyğunsunuz


In [18]:
# İki ədəd təyin edir
x = 10
y = 20

# x və y arasından kiçik olanı seçir
# Əgər x < y-dirsə, kiçik = x olacaq, əks halda kiçik = y olacaq
kiçik = x if x < y else y

# Nəticəni çap edir
print("Kiçik olan:", kiçik)

Kiçik olan: 10


# 1.3 Dövrlər

Dövrlər proqramda eyni əmri çoxsaylı dəfə təkrar etmək üçün istifadə olunur.
Məsələn, əgər sən 10 dəfə “Salam” demək istəyirsənsə, dövr həmin əmri 10 dəfə avtomatik yerinə yetirir.
Bu, əl ilə hər dəfə yazmaq yerinə işimizi asanlaşdırır və vaxt qənaət edir.
Dövr başladıqda təyin olunan sayda və ya şərtə görə əmrləri təkrar edir.
Beləliklə, proqram eyni işi çoxsaylı dəfə təkrarlamağa imkan verir.
`types: for and while.`
Aşağıda bunları daha yaxşı anlamaq üçün nümunələr verilib.

Ekrana əvvəlcə **"0-dan 4-ə qədər:"** yazısı çıxır.  
`for` dövrü **0-dan başlayaraq 4-ə qədər** (5 daxil deyil) olan ədədləri təkrar-təkrar çap edir.  
`range(5)` funksiyası 0-dan 4-ə qədər olan ədədlər ardıcıllığını yaradır.  
`print(i, end=' ')` əmri ədədləri boşluqla ayıraraq, hər biri yeni sətrə keçmədən ekrana yazır.  
Nəticədə ekranda: `0 1 2 3 4` çap olunur.  


In [20]:
# Ekrana "0-dan 4-ə qədər:" yazdırır
print("0-dan 4-ə qədər:")

# 0-dan başlayaraq 4-ə qədər (5 daxil deyil) ədədləri çap edir
for i in range(5):
    # i dəyərini boşluqla ayıraraq çap edir (new line olmadan)
    print(i, end=' ')


0-dan 4-ə qədər:
0 1 2 3 4 

Ekrana əvvəlcə **"5-dən 9-a qədər:"** yazılır.  
`for` dövrü **5-dən başlayaraq 9-a qədər** ədədləri çap edir.  
`range(5, 10)` funksiyası 5-dən 9-a qədər (10 daxil deyil) ədədləri yaradır.  
`print(i, end=' ')` ədədləri boşluqla ayırır və yeni sətirə keçmir.  
Nəticədə ekranda: `5 6 7 8 9` göstərilir.  

In [21]:
print("\n\n5-dən 9-a qədər:")
for i in range(5, 10):
    print(i, end=' ')




5-dən 9-a qədər:
5 6 7 8 9 

Ekrana əvvəlcə **"0-dan 10-a qədər 2 addım:"** yazılır.  
`for` dövrü **0-dan başlayaraq 10-a qədər 2 addımla** ədədləri çap edir.  
`range(0, 11, 2)` funksiyası 0-dan 10-a qədər (11 daxil deyil), 2 addımla ardıcıllıq yaradır.  
`print(i, end=' ')` ədədləri boşluqla ayırır və yeni sətrə keçmir.  
Nəticədə ekranda: `0 2 4 6 8 10` göstərilir.  


In [22]:
print("\n\n0-dan 10-a qədər 2 addım:")
for i in range(0, 11, 2):
    print(i, end=' ')



0-dan 10-a qədər 2 addım:
0 2 4 6 8 10 

`meyvələr` siyahısında müxtəlif meyvə adları saxlanılır.  
`for` dövrü siyahıdakı hər bir meyvəni tək-tək götürür və `meyvə` dəyişəninə verir.  
`print(meyvə)` hər meyvənin adını ekrana çap edir.
Bu proses siyahıdakı bütün meyvələr üçün təkrarlanır.  
Nəticədə meyvə adları sətir-sətir böyük hərflə başlayaraq göstərilir.  


In [ ]:
meyvələr = ["alma", "armud", "banan", "nar"]
print("\n\nMeyvələr siyahısı:")
for meyvə in meyvələr:
    print(meyvə)



Meyvələr siyahısı:
Alma
Armud
Banan
Nar


`enumerate(meyvələr)` funksiyası siyahıdakı hər elementlə birlikdə onun indeksini də verir.  
`for` dövründə həm `indeks`, həm də `meyvə` dəyişənləri təyin olunur.  
`print(f"{indeks}: {meyvə}")` hər meyvəni onun indeks nömrəsi ilə birlikdə ekrana yazdırır.  
Bu üsul siyahıdakı elementlərin yerlərini və adlarını birlikdə göstərməyə imkan verir.  
Nəticədə, meyvələr və onların indeksləri nömrə:ad şəklində çıxır.  


In [24]:
# İndeks və dəyərlə birlikdə
print("\nMeyvələr və indekslər:")
for indeks, meyvə in enumerate(meyvələr):
    print(f"{indeks}: {meyvə}")


Meyvələr və indekslər:
0: alma
1: armud
2: banan
3: nar


## While dövrü nümunələri

while dövrü bir şərt doğru (True) olduğu müddətcə işləyən dövrdür. while dövrü, əvvəlcədən neçə dəfə işləyəcəyi bilinməyən hallarda, bir şərt doğru olduğu müddətcə işləyir.for dövrü isə adətən siyahı, sıra və ya müəyyən sayda təkrarlanacaq əməliyyatlar üçün istifadə olunur.

`say` dəyişəni 0 olaraq təyin edilir.  
`while` dövrü `say` 5-dən kiçik olduğu müddətcə işləyir.  
Dövr daxilində `say`-ın cari dəyəri boşluqla ayrılaraq ekrana çap olunur.  
Hər dəfə dövr işlədikcə `say` 1 vahid artırılır (`say += 1`).  
Dövr `say` 5-ə çatanda dayanar və ekranda `0 1 2 3 4` çap olunur.  

In [25]:
# say dəyişənini 0 olaraq təyin edir
say = 0

# Başlıq olaraq "While dövrü:" yazdırır
print("\nWhile dövrü:")

# say 5-dən kiçik olduğu müddətcə dövrü işləyir
while say < 5:
    # say dəyişəninin cari dəyərini boşluqla ayrılmış şəkildə çap edir
    print(say, end=' ')
    # say dəyişəninin dəyərini 1 artırır
    say += 1


While dövrü:
0 1 2 3 4 

- `say` dəyişəni 0 olaraq təyin edilir.  
- `while` dövrü `say < 5` şərti doğru olduqca işləyir.  
- Dövr daxilində `say`-ın cari dəyəri boşluqla çap olunur.  
- Hər iterasiyada `say` dəyişəni 1 artırılır (`say += 1`).  
- `say` dəyəri 5-ə çatdıqda şərt səhv olur və dövr dayanır, `break` dovru durdurur.


In [26]:
# break və continue
print("\n\nBreak nümunəsi:")
say = 0
while True:
    print(say, end=' ')
    say += 1
    if say >= 5:
        break




Break nümunəsi:
0 1 2 3 4 

- `say` dəyişəni 0 olaraq təyin edilir.  
- `while` dövrü `say < 10` şərti ilə işləyir.  
- Hər iterasiyada `say` 1 vahid artırılır.  
- `say` ədədi cütdürsə, `continue` əmri işləyir və `print()` yerinə yetirilmir.
- Nəticədə yalnız tək ədədlər (`1 3 5 7 9`) çap olunur.  


In [ ]:
#continue əmriylə biz bir nov bundan kec ve davam et deyirik
print("\n\nContinue nümunəsi:")
say = 0
while say < 10:
    say += 1
    if say % 2 == 0:
        continue
    print(say, end=' ')



Continue nümunəsi:
1 3 5 7 9 

## 2.1 Listlər

List (və ya siyahı) Python-da müxtəlif məlumatları bir yerdə saxlamaq üçün istifadə olunan verilənlər tipidir.(Digər tiplərdən fərqi ondadır ki, dəyişə bilən, sıralıdır, həmçinin daxilində təkrarlanma ola bilir.)

- `boş_list` adlı boş bir siyahı yaradılır.  
- `rəqəmlər` siyahısı yalnız tam ədədlərdən ibarətdir.  
- `qarışıq` adlı siyahıda müxtəlif tipli elementlər (tam ədəd, string, float, boolean) mövcuddur.  
- `list_from_range` `range(10)` funksiyası ilə 0-dan 9-a qədər ədədlərlə dolu siyahı yaradır.  
- `list_from_string` isə `"Python"` sözünü simvollara ayıraraq siyahıya çevirir: `['P', 'y', 't', 'h', 'o', 'n']`.  


In [29]:
boş_list = []
rəqəmlər = [1, 2, 3, 4, 5]
qarışıq = [1, "iki", 3.0, True]
list_from_range = list(range(10))
list_from_string = list("Python")

print("Rəqəmlər:", rəqəmlər)
print("Qarışıq list:", qarışıq)
print("Range-dən list:", list_from_range)
print("String-dən list:", list_from_string)

Rəqəmlər: [1, 2, 3, 4, 5]
Qarışıq list: [1, 'iki', 3.0, True]
Range-dən list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
String-dən list: ['P', 'y', 't', 'h', 'o', 'n']


## İndexlərlə list elementlərinə çatmaq

Bütün collectionlarda indexləmə 0`dan başlayır, bu da rəqəmlərin sayı ilə index qiymətləri arasında 1 vahid fərq deməkdir. Hər zaman nəzərə alın!!!

In [ ]:
my_list = [1, 2, 3, 4, 5]

In [ ]:
print("İlk element:", my_list[0])       # 1
print("Son element:", my_list[-1])      # 5
print("Son element:", my_list[1])      # 2
print("Son element:", my_list[3])      # 4

### List slicing
- `my_list[1:3]` ikinci və üçüncü elementləri (index 1 və 2) alır: `[2, 3]`.
- `my_list[:3]` başlanğıcdan 3-cü indexə qədər olan elementləri qaytarır: `[1, 2, 3]`.
- `my_list[3:]` dördüncü elementdən sona qədər olan hissəni verir: `[4, 5]`.
- `my_list[::2]` isə hər ikinci elementi götürərək addımlı slicing edir: `[1, 3, 5]`.


In [ ]:
my_list = [1, 2, 3, 4, 5]

In [ ]:
print("Slice 1-3:", my_list[1:3])      # [2, 3]
print("Slice başdan:", my_list[:3])     # [1, 2, 3]
print("Slice sona:", my_list[3:])       # [4, 5]
print("Addımlı slice:", my_list[::2])   # [1, 3, 5]


İlk element: 1
Son element: 5
Slice 1-3: [2, 3]
Slice başdan: [1, 2, 3]
Slice sona: [4, 5]
Addımlı slice: [1, 3, 5]


In [ ]:
meyvələr = ["alma", "banan",]

- `append("nar")` funksiyası "nar" sözünü siyahının **sonuna** əlavə edir.
- `insert(1, "armud")` funksiyası "armud" sözünü **1-ci index**-ə (yəni **ikinci yerə**) yerləşdirir.
- Nəticə olaraq, siyahı belə olur: `["alma", "armud", "banan", "nar"]`


In [33]:
meyvələr.append("nar")         # Sonuna əlavə
meyvələr.insert(1, "armud")    # Müəyyən yerə
print("Əlavədən sonra:", meyvələr)

Əlavədən sonra: ['alma', 'armud', 'banan', 'nar']


- `pop(1)` funksiyası siyahıdan 1-ci indeksdəki elementi silir və həmin elementi geri qaytarır.  
- Bu nümunədə `meyvələr.pop(1)` 1-ci indeksdəki elementi (məsələn, "armud") siyahıdan çıxarır.  
- `remove("banan")` funksiyası isə siyahıdan ilk qarşılaşılan "banan" elementini silir.  
- `pop` metodu silinən elementi dəyişkənə qaytarır, `remove` isə sadəcə elementi siyahıdan silir.  
- Çap olunan nəticələr silinmiş elementləri və qalan siyahını göstərir.


In [34]:
# Silmə
çıxarılan = meyvələr.pop(1)    # İndekslə sil
print(f"Çıxarılan: {çıxarılan}, Qalan: {meyvələr}")
meyvələr.remove("banan")       # Dəyərlə sil
print("Silmədən sonra:", meyvələr)


Çıxarılan: armud, Qalan: ['alma', 'banan', 'nar']
Silmədən sonra: ['alma', 'nar']


- `sort()` funksiyası siyahını **artma sırasına** görə nizamlayır.  
- Bu nümunədə `rəqəmlər.sort()` siyahını `[1, 2, 3, 4]` halına gətirir.  
- `reverse()` funksiyası siyahını **əksinə çevirir**, yəni elementlərin sırasını tərsinə dəyişir.  
- `rəqəmlər.reverse()` tətbiqindən sonra siyahı `[4, 3, 2, 1]` olur.  
- Hər iki əməliyyat siyahını yerində dəyişdirir və yeni siyahı qaytarmır.


In [35]:
# Digər əməliyyatlar
rəqəmlər = [3, 1, 4, 2]
rəqəmlər.sort()                # Çeşidləmə
print("Çeşidlənmiş:", rəqəmlər)
rəqəmlər.reverse()             # Tərsinə çevirmə
print("Tərs:", rəqəmlər)

Çeşidlənmiş: [1, 2, 3, 4]
Tərs: [4, 3, 2, 1]


## Listlərin birləşdirilmə üsulları

İki siyahını birləşdirmək üçün müxtəlif üsullar mövcuddur.  
`+` operatoru yeni bir siyahı yaradır, əsas siyahılar dəyişmir.  
`.extend()` metodu ikinci siyahını birincinin sonuna əlavə edir və birbaşa onu dəyişir.  
`for` dövrü ilə elementlər tək-tək `append()` ilə əlavə olunur.  
`*` operatoru ilə hər iki siyahı açılaraq yeni bir siyahı yaradılır.  
Hər üsul fərqli məqsədlər üçün istifadə olunur və nəticə eyni ola bilər.  

In [ ]:
siyahi1 = [1, 2, 3]
siyahi2 = [4, 5, 6]
birlesmis_siyahi = siyahi1 + siyahi2
print(birlesmis_siyahi)  # Nəticə: [1, 2, 3, 4, 5, 6]
siyahi1.extend(siyahi2)
print(siyahi1)  # Nəticə: [1, 2, 3, 4, 5, 6]
for element in siyahi2:
    siyahi1.append(element)
print(siyahi1)  # Nəticə: [1, 2, 3, 4, 5, 6]
birlesmis_siyahi = [*siyahi1, *siyahi2]
print(birlesmis_siyahi)  # Nəticə: [1, 2, 3, 4, 5, 6]

## List Comprehensions

 Python-da List Comprehensions — siyahılar üçün qısa və səmərəli yazılış üsuludur.

- Bu kod 0-dan 9-a qədər ədədlərin kvadratlarını `kvadratlar` siyahısına əlavə edir.  
- `for` dövrü hər `x` üçün `x**2` (x-in kvadratı) hesablayır və siyahıya əlavə edir.  
- Nəticədə `kvadratlar` siyahısı `[0, 1, 4, 9, ..., 81]` kimi kvadrat ədədlərdən ibarət olur.  
- Bu üsul siyahı yaratmaq üçün ənənəvi dövr metodudur.  
- Daha qısa yazmaq üçün list anlayışlarından istifadə edə bilərik.



In [38]:
kvadratlar = []
for x in range(10):
    kvadratlar.append(x**2)
print(kvadratlar)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


- Bu kod list anlayışından istifadə edərək 0-dan 9-a qədər ədədlərin kvadratlarını yaradır.  
- Hər `x` üçün `x**2` hesablanır və yeni siyahıya əlavə olunur.  
- Nəticədə `kvadratlar` siyahısı `[0, 1, 4, 9, ..., 81]` şəklində olur.  
- List anlayışları kodu daha qısa və oxunaqlı edir.  
- Eyni işi ənənəvi `for` dövrü ilə daha uzun yazmaq olar.


In [37]:
kvadratlar = [x**2 for x in range(10)]
print("Kvadratlar:", kvadratlar)

Kvadratlar: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [39]:
cüt_ədədlər = [x for x in range(20) if x % 2 == 0]
print("Cüt ədədlər:", cüt_ədədlər)

Cüt ədədlər: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [40]:
nəticələr = ["çox yaxşı" if x > 85 else "yaxşı" if x > 70 else "kafi" for x in [90, 75, 60]]
print("Nəticələr:", nəticələr)


Nəticələr: ['çox yaxşı', 'yaxşı', 'kafi']


## 2.2 Dictionary

Dictionary — məlumatları “açar: dəyər” (key: value) cütləri şəklində saxlayan verilənlər tipidir. Hər bir açar (key) özünə aid bir dəyəri (value) göstərir.

- `range(10)` funksiyası 0-dan 9-a qədər ədədləri yaradır.  
- `x**2` ifadəsi hər ədədin kvadratını hesablayır.  
- `for x in range(10)` dövrü bu ədədləri bir-bir götürür.  
- `[]` içində dövr yazaraq **list comprehension** istifadə edilir.  
- Nəticə `kvadratlar` adlı siyahıya yazılır və çap edilir.


In [41]:
boş_lüğət = {}
şagird = {
    "ad": "Əli",
    "yaş": 20,
    "ixtisas": "İnformatika",
    "fənnlər": ["Proqramlaşdırma", "Verilənlər Bazası"]
}

print("Tam lüğət:", şagird)
print("Ad:", şagird["ad"])
print("İlk fənn:", şagird["fənnlər"][0])

Tam lüğət: {'ad': 'Əli', 'yaş': 20, 'ixtisas': 'İnformatika', 'fənnlər': ['Proqramlaşdırma', 'Verilənlər Bazası']}
Ad: Əli
İlk fənn: Proqramlaşdırma


- `şagird.keys()` lüğətin bütün **açarlarını** qaytarır.  
- `şagird.values()` lüğətin bütün **dəyərlərini** verir.  
- `şagird.items()` isə həm **açar**, həm də **dəyər cütlərini** qaytarır.  
- `print(...)` funksiyası bu nəticələri ekrana çıxarır.  
- Bu metodlar lüğətin strukturunu analiz etmək üçün faydalıdır.


In [42]:
print("Açarlar:", şagird.keys())
print("Dəyərlər:", şagird.values())
print("Cütlər:", şagird.items())

Açarlar: dict_keys(['ad', 'yaş', 'ixtisas', 'fənnlər'])
Dəyərlər: dict_values(['Əli', 20, 'İnformatika', ['Proqramlaşdırma', 'Verilənlər Bazası']])
Cütlər: dict_items([('ad', 'Əli'), ('yaş', 20), ('ixtisas', 'İnformatika'), ('fənnlər', ['Proqramlaşdırma', 'Verilənlər Bazası'])])


- `şagird["universitet"] = "BDU"` ilə lüğətə yeni **açar-dəyər cütü** əlavə edilir.  
- Burada `universitet` açarı, `"BDU"` isə ona uyğun dəyərdir.  
- Bu əməliyyat mövcud lüğətə yeni məlumat əlavə etmək üçündür.  
- `print()` funksiyası dəyişdirilmiş lüğəti ekrana çıxarır.  
- Nəticədə lüğət əvvəlkindən daha çox məlumat ehtiva edir.


In [43]:
şagird["universitet"] = "BDU"
print("\nƏlavədən sonra:", şagird)


Əlavədən sonra: {'ad': 'Əli', 'yaş': 20, 'ixtisas': 'İnformatika', 'fənnlər': ['Proqramlaşdırma', 'Verilənlər Bazası'], 'universitet': 'BDU'}


- `şagird.pop("yaş")` ilə lüğətdən `"yaş"` açarı və onun dəyəri silinir.  
- Silinən dəyər `silinən` dəyişənində saxlanılır və çap edilir.  
- `print()` funksiyası həm silinmiş dəyəri, həm də qalan lüğəti göstərir.  
- Bu üsul açar və dəyəri eyni anda lüğətdən çıxarmağa imkan verir.  


In [44]:
silinən = şagird.pop("yaş")
print(f"Silinən: {silinən}, Qalan: {şagird}")

Silinən: 20, Qalan: {'ad': 'Əli', 'ixtisas': 'İnformatika', 'fənnlər': ['Proqramlaşdırma', 'Verilənlər Bazası'], 'universitet': 'BDU'}


- `ədədlər` siyahısı 1-dən 5-ə qədər ədədləri ehtiva edir.  
- `{x: x**2 for x in ədədlər}` ifadəsi hər ədəd üçün onun kvadratını açar-dəyər cütü şəklində yaradır.  
- Bu, **dictionary comprehension** adlanır və lüğət yaratmaq üçün qısa yazılışdır.  
- Nəticədə `kvadrat_lüğəti` adlı lüğətdə hər ədədin kvadratı saxlanır.  
- `print()` funksiyası bu lüğəti ekrana çıxarır.


In [45]:
# Ədədlər siyahısı yaradır
ədədlər = [1, 2, 3, 4, 5]

# Siyahıdakı hər ədədin kvadratını açar-dəyər cütlüyü kimi saxlayan lüğət (dictionary) yaradır
kvadrat_lüğəti = {x: x**2 for x in ədədlər}

# Nəticədə yaranan kvadrat lüğətini çap edir
print("Kvadrat lüğəti:", kvadrat_lüğəti)

Kvadrat lüğəti: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


- `kvadrat_lüğəti.items()` ilə lüğətdəki bütün açar-dəyər cütləri götürülür.  
- `if v % 2 == 0` şərti ilə yalnız **cüt kvadrat dəyərləri** seçilir.  
- Yeni lüğət yalnız cüt kvadratlardan ibarət olur.  
- Bu, filtr tətbiq etmək üçün dictionary comprehension nümunəsidir.  
- `print()` funksiyası nəticəni ekrana verir.

In [46]:
# kvadrat_lüğəti lüğətində olan cüt kvadrat dəyərləri seçib yeni lüğət yaradır
# yəni, kvadratın 2-yə bölünəndən 0 qalığı varsa, onu saxlayır
cüt_lüğət = {k: v for k, v in kvadrat_lüğəti.items() if v % 2 == 0}

# Nəticədə yaranan cüt kvadratlar lüğətini çap edir
print("Cüt kvadratlar:", cüt_lüğət)

Cüt kvadratlar: {2: 4, 4: 16}


Python-da iki `dict` (sözlük) müxtəlif yollarla birləşdirilə bilər.  
`update()` metodu ilə bir sözlük digərinə əlavə olunur və orijinal dəyişə bilər.  
`**` operatoru ilə iki `dict` yeni bir sözlük kimi birləşdirilir.  
Python 3.9 və sonrası üçün `|` operatoru da istifadə oluna bilər.  
Klassik üsul olaraq `items()` və `dict()` ilə də birləşdirmək mümkündür.  
Əgər eyni açar varsa, sonuncu sözlükdəki dəyər üstün tutulur.


In [ ]:
# İki dict (sözlük) nümunəsi
dict1 = {"ad": "Kənan", "yas": 21}
dict2 = {"ölkə": "Azərbaycan", "yas": 22}

# 1. update() metodu ilə (birbaşa dict1 dəyişir)
dict_a = dict1.copy()
dict_a.update(dict2)
print("1. update() metodu ilə:", dict_a)
# Nəticə: {'ad': 'Kənan', 'yas': 22, 'ölkə': 'Azərbaycan'}

# 2. ** operatoru ilə birləşdirmə (yeni dict yaradılır)
birlesmis1 = {**dict1, **dict2}
print("2. ** operatoru ilə:", birlesmis1)
# Nəticə: {'ad': 'Kənan', 'yas': 22, 'ölkə': 'Azərbaycan'}

# 3. | operatoru ilə birləşdirmə (yalnız Python 3.9 və sonrası)
birlesmis2 = dict1 | dict2
print("3. | operatoru ilə:", birlesmis2)
# Nəticə: {'ad': 'Kənan', 'yas': 22, 'ölkə': 'Azərbaycan'}

# 4. items() və dict() ilə (klassik metod)
birlesmis3 = dict(list(dict1.items()) + list(dict2.items()))
print("4. items() + dict() ilə:", birlesmis3)
# Nəticə: {'ad': 'Kənan', 'yas': 22, 'ölkə': 'Azərbaycan'}


## 2.3 Setler(Çoxluqlar)

Set — unikal, yəni təkrarlanmayan elementlərdən ibarət, sırasız verilənlər toplusudur. Listlərdən fərqli olaraq indexlərə malik deyil və içərisində eyni elementlər olmamalıdır!!!

- `çoxluq` dəyişəni **set** (çoxluq) tipində yaradılır.  
- Set-də təkrarlanan elementlər yalnız bir dəfə saxlanılır.  
- Bu nümunədə `3` və `4` iki dəfə yazılsa da, nəticədə yalnız bir dəfə görünür.  
- Set-lər unikal elementləri saxlamaq üçün istifadə olunur.  
- `print()` funksiyası çoxluğu ekrana çıxarır.


In [47]:
çoxluq = {1, 2, 3, 3, 4, 4}
print("Çoxluq:", çoxluq)  # {1, 2, 3, 4}


Çoxluq: {1, 2, 3, 4}


- `A` və `B` çoxluqları yaradılır, hər biri unikal elementlərdən ibarətdir.  
- `A.union(B)` hər iki çoxluğun elementlərini birləşdirir və təkrarlananları silir.  
- `A.intersection(B)` hər iki çoxluqda olan ortaq elementləri göstərir.  
- `A.difference(B)` yalnız `A`-da olub `B`-də olmayan elementləri tapır.  
- `A.symmetric_difference(B)` isə hər iki çoxluqda olan, amma ortaq olmayan elementləri qaytarır.

In [48]:
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}

print("Birləşmə:", A.union(B))            # {1, 2, 3, 4, 5, 6}
print("Kəsişmə:", A.intersection(B))      # {3, 4}
print("Fərq (A-B):", A.difference(B))     # {1, 2}
print("Simmetrik fərq:", A.symmetric_difference(B))  # {1, 2, 5, 6}


Birləşmə: {1, 2, 3, 4, 5, 6}
Kəsişmə: {3, 4}
Fərq (A-B): {1, 2}
Simmetrik fərq: {1, 2, 5, 6}


## 2.4 Tuple

Tuple — sıralı, amma dəyişdirilməyən (immutable) verilənlər toplusudur. Yəni, yaradıldıqdan sonra içindəki elementləri dəyişmək olmaz.

- `koordinat` dəyişəni **tuple** olaraq yaradılır, yəni dəyişdirilməz verilənlər cütü.  
- Tuple içində Bakı şəhərinin enlik və uzunluq koordinatları saxlanılır.  
- `print()` ilə tuple və onun elementləri göstərilir.  
- `koordinat[0]` enlik, `koordinat[1]` isə uzunluq dəyəridir.  
- Tuple-lar dəyişdirilə bilmədiyi üçün koordinat kimi sabit məlumatlar üçün uyğundur.


In [2]:
koordinat = (40.4093, 49.8671)  # Bakı koordinatları
print("Tuple:", koordinat)
print("Enlik:", koordinat[0])
print("Uzunluq:", koordinat[1])

Tuple: (40.4093, 49.8671)
Enlik: 40.4093
Uzunluq: 49.8671


In [3]:
koordinat[0] = "yoxlama"

TypeError: 'tuple' object does not support item assignment

- `koordinat` tuple-dakı elementlər `enlik` və `uzunluq` adlı dəyişənlərə ayrılır (unpacking edilir).  
- Bu yolla tuple-dakı məlumatlara asanlıqla fərdi dəyişənlər kimi daxil olmaq mümkündür.  
- `print()` funksiyası ilə enlik və uzunluq formatlanmış şəkildə ekrana çıxarılır.  
- `f-string` formatı dəyişənləri mətn içində göstərməyə imkan verir.  
- Bu üsul tuple və digər kolleksiyalar üçün rahat verilən ayırma (unpacking) üsuludur.


In [50]:
enlik, uzunluq = koordinat
print(f"Enlik: {enlik}, Uzunluq: {uzunluq}")

Enlik: 40.4093, Uzunluq: 49.8671


## Funksiyalar

Funksiya — müəyyən bir işi yerinə yetirən, təkrar istifadə edilə bilən kod blokudur. Funksiyalar proqramı daha səliqəli, oxunaqlı və idarəolunan edir.

- `kvadrat` adlı funksiya bir ədəd `x` qəbul edir və onun kvadratını hesablayır.  
- Funksiya daxilində `return` əmri ilə `x`-in özü ilə vurulması qaytarılır.  
- Funksiya sənədləşdirilməsi üçün `""" """` içində qısa şərh yazılıb.  
- `print()` funksiyası ilə `kvadrat(5)` çağırılıb və 5-in kvadratı ekrana çıxarılır.  
- Bu funksiya təkrar istifadə üçün yazılmış sadə riyazi əməliyyat nümunəsidir.

In [5]:
def kvadrat(x):
    """Verilən ədədin kvadratını qaytarır"""
    return x ** 2

print("5-in kvadratı:", kvadrat(5))

5-in kvadratı: 25


Aşağıda funksiyanın qiymətinin dəyişkənə mənimsədilmə prinsipi açıqlanırş

In [7]:
deyer_saxlama = kvadrat(4)
print(deyer_saxlama) # burada funksiyanın dəyərinin dəyişənlə saxlanılması göstərilir. 

16


- `ünvan_yarat` funksiyası `ad`, `şəhər` və `ölkə` parametrlərini qəbul edir.  
- `şəhər` və `ölkə` üçün standart dəyərlər verilib: `Bakı` və `Azərbaycan`.  
- Funksiya daxilində verilən ad, şəhər və ölkə birləşdirilərək ünvan formatında qaytarılır.  
- Əgər `şəhər` və ya `ölkə` verilməzsə, standart dəyərlər istifadə olunur.  
- Bu funksiya ünvan yaratmaq üçün rahat və çevik vasitədir.

In [9]:
def ünvan_yarat(ad, şəhər="Bakı", ölkə="Azərbaycan"):
    """Ünvan yaradır"""
    return f"{ad}, {şəhər}, {ölkə}"

In [ ]:
print(ünvan_yarat("Əli"))
print(ünvan_yarat("Aygün", "Gəncə"))
print(ünvan_yarat("John", "London", "İngiltərə"))
print(ünvan_yarat("John", şəhər="London", ölkə="İngiltərə")) #Bilinməsi faydalıdır. Belə qiymət mənimsətmə vardır.

Əli, Bakı, Azərbaycan
Aygün, Gəncə, Azərbaycan
John, London, İngiltərə


In [ ]:
print(ünvan_yarat()) # Heç bir dəyər verilmədikdə belə problem yaranır.

TypeError: ünvan_yarat() missing 1 required positional argument: 'ad'

Burada * ve ** pointerlərdir(Pointer, kompüterdəki bir dəyərin saxlandığı ünvanı göstərən dəyişəndir. Sən pointer ilə dəyərin özünü deyil, onun yerini (ünvanını) yadda saxlayırsan. Bu, bir kitabın səhifə nömrəsini bilmək kimidir – kitabın içindəki məlumatı oxumaq üçün ora baxırsan. Pointerlər proqramın daha səmərəli işləməsinə və verilərin birbaşa üzərində işləməyə imkan verir. Onlarla səhv işləmək isə proqram səhvlərinə səbəb ola bilər, çünki birbaşa yaddaşa müdaxilə edilir.). Limitsiz number almaq olur. * , ** arasındaki fərq tək ulduzun yalnızca qiymətlər almasıdır. Siz funksiyada bunu istifadə edərək təkcə rəqəmlər listi ötürə bilərsiz amma iki ulduzca key value prinsipi, hansı ki, bir dictionary mövzusunda danışdıq artıq. İstəsəz yuxarıdan baxa bilərsiz.

In [54]:
def cəmi_hesabla(*rəqəmlər):
    """Verilən bütün rəqəmlərin cəmini hesablayır"""
    return sum(rəqəmlər)

In [55]:
print("Cəmi (1,2,3):", cəmi_hesabla(1, 2, 3))
print("Cəmi (4,5,6,7):", cəmi_hesabla(4, 5, 6, 7))

Cəmi (1,2,3): 6
Cəmi (4,5,6,7): 22


- `şagird_məlumatı` funksiyası `**məlumat` ilə istənilən sayda açar-dəyər cütü qəbul edir.  
- `**` operatoru, funksiyaya açar-dəyər şəklində verilən çoxsaylı arqumentləri lüğət (dictionary) kimi ötürür.  
- Funksiya daxilində `məlumat.items()` ilə bütün açar və dəyərlər əldə edilir və `for` dövrü ilə hər biri çap olunur.  
- Bu üsul funksiya çağırarkən dəyişkən sayda parametr verməyə imkan yaradır.  
- Məsələn, `şagird_məlumatı(ad="Əli", yaş=20, ixtisas="İnformatika")` çağırışı həmin açar-dəyərləri ekrana yazdırır.

In [56]:
def şagird_məlumatı(**məlumat):
    """Şagird haqqında məlumat çap edir"""
    for açar, dəyər in məlumat.items():
        print(f"{açar}: {dəyər}")

şagird_məlumatı(ad="Əli", yaş=20, ixtisas="İnformatika")

ad: Əli
yaş: 20
ixtisas: İnformatika


- `lambda` ilə qısa, anonim (adlandırılmamış) funksiya yaradılır; burada `x`-in kvadratı hesablanır.  
- `kvadrat(4)` çağırışı 4-ün kvadratını (16) qaytarır və çap edilir.  
- `şagirdlər` siyahısı hər biri `ad` və `bal` açarlarına sahib lüğətlərdən ibarətdir.  
- Bu siyahı şagirdlərin adlarını və ballarını saxlayır.  
- Lambda funksiyası tez-tez `sorted()` və ya `map()` kimi funksiyalarla birlikdə istifadə olunur.

In [57]:
# Lambda funksiyası ilə verilən ədədin kvadratını hesablayan funksiya yaradır
kvadrat = lambda x: x ** 2

# Lambda funksiyasını çağırıb 4-ün kvadratını çap edir
print("Lambda kvadrat:", kvadrat(4))

# Şagirdlərin ad və ballarını saxlayan siyahı (dictionary-lərdən ibarət)
şagirdlər = [
    {"ad": "Əli", "bal": 85},
    {"ad": "Aygün", "bal": 92},
    {"ad": "Vaqif", "bal": 78}
]

Lambda kvadrat: 16


- `sorted()` funksiyası `şagirdlər` siyahısını `bal` açarına görə azalan qaydada sıralayır.  
- `key=lambda x: x["bal"]` hər şagirdin balına əsaslanaraq sıralama aparır.  
- `reverse=True` ilə sıralama tərs, yəni böyükdən kiçiyə doğru olur.  
- Nəticədə `sıralanmış` siyahısı bal üzrə azalan qaydada olur.  
- Sonra `for` dövrü ilə hər bir şagird çap edilir.

In [58]:
sıralanmış = sorted(şagirdlər, key=lambda x: x["bal"], reverse=True)
print("Balına görə sıralanmış şagirdlər:")
for şagird in sıralanmış:
    print(şagird)


Balına görə sıralanmış şagirdlər:
{'ad': 'Aygün', 'bal': 92}
{'ad': 'Əli', 'bal': 85}
{'ad': 'Vaqif', 'bal': 78}


## Fayl I/O

Fayl I/O — fayllarla oxuma və yazma əməliyyatlarını yerinə yetirməkdir. Bu, məlumatları kompüterdə saxlamaq və ya onlardan oxumaq üçün istifadə olunur.

- `'nümunə.txt'` adlı fayl yazmaq üçün açılır, mövcud deyilsə yaradılır, UTF-8 kodlaşdırması istifadə olunur.  
- `with open(..., 'w', encoding='utf-8') as f:` bloku fayl avtomatik bağlanana qədər işləyir.  
- Fayla üç sətir yazılır, hər sətrin sonunda `\n` ilə yeni sətir əlavə edilir.  
- Daha sonra eyni fayl oxumaq üçün açılır və məzmunu `print(f.read())` ilə ekrana çıxarılır.  
- Bu üsul fayl əməliyyatlarını sadə və təhlükəsiz idarə etməyə imkan verir.


In [59]:
# 'nümunə.txt' adlı faylı yazmaq üçün açır (mövcud deyilsə yaradılır), UTF-8 kodlaşdırması ilə
with open('nümunə.txt', 'w', encoding='utf-8') as f:
    # Fayla üç sətir yazır, hər sətrin sonunda yeni sətir simvolu (\n) əlavə olunur
    f.write("Bu birinci sətirdir.\n")
    f.write("Bu ikinci sətirdir.\n")
    f.write("Bu üçüncü sətirdir.\n")

# Fayldan oxumaq üçün açır və məzmunu çap edir
print("\nFaylın tam məzmunu:")
with open('nümunə.txt', 'r', encoding='utf-8') as f:
    print(f.read())


Faylın tam məzmunu:
Bu birinci sətirdir.
Bu ikinci sətirdir.
Bu üçüncü sətirdir.



- Faylın başlığı olaraq "Fayl sətir-sətir:" ekrana yazdırılır.  
- `'nümunə.txt'` faylı oxumaq üçün UTF-8 kodlaşdırması ilə açılır.  
- `for` dövrü ilə fayldakı hər sətrin üzərində tək-tək gəzilir.  
- `sətir.strip()` ilə sətrin əvvəlində və sonundakı boşluqlar və yeni sətir simvolu (`\n`) silinir.  
- Hər təmizlənmiş sətir ayrıca ekrana çap olunur.


In [60]:
# Ekrana "Fayl sətir-sətir:" başlığını yazdırır
print("\nFayl sətir-sətir:")

# 'nümunə.txt' faylını oxumaq üçün açır, UTF-8 kodlaşdırması ilə
with open('nümunə.txt', 'r', encoding='utf-8') as f:
    # Fayldakı hər sətri bir-bir oxuyur
    for sətir in f:
        # Hər sətrin əvvəlində və sonunda olan boşluqları və yeni sətir simvolunu silərək çap edir
        print(sətir.strip())


Fayl sətir-sətir:
Bu birinci sətirdir.
Bu ikinci sətirdir.
Bu üçüncü sətirdir.


- `csv` modulu CSV faylları ilə işləmək üçün import edilir.  
- `'şagirdlər.csv'` faylı yazmaq üçün açılır, `newline=''` əlavə boş sətirlərin qarşısını alır.  
- `csv.writer` ilə yazıcı yaradılır və başlıq sətri daxil olmaqla məlumatlar yazılır.  
- Fayl yazıldıqdan sonra oxumaq üçün açılır və `csv.reader` ilə oxuyucu yaradılır.  
- `for` dövrü ilə hər sətrin məzmunu siyahı kimi ekrana çap olunur.

In [61]:
# csv modulunu import edir (CSV faylları ilə işləmək üçün)
import csv

# 'şagirdlər.csv' faylını yazmaq üçün açır, newline='' - əlavə boş sətirlərin qarşısını almaq üçün
with open('şagirdlər.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)  # CSV yazıcısını yaradır
    writer.writerow(["Ad", "Yaş", "İxtisas"])  # Başlıq sətrini yazır
    writer.writerow(["Əli", 20, "İnformatika"])  # Birinci şagird məlumatları
    writer.writerow(["Aygün", 21, "Riyaziyyat"])  # İkinci şagird məlumatları

# CSV faylını oxumaq və məzmunu çap etmək
print("\nCSV fayl məzmunu:")
with open('şagirdlər.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)  # CSV oxuyucusunu yaradır
    for sətir in reader:
        print(sətir)  # Hər sətri siyahı şəklində çap edir


CSV fayl məzmunu:
['Ad', 'Yaş', 'İxtisas']
['Əli', '20', 'İnformatika']
['Aygün', '21', 'Riyaziyyat']


## Error handling

Error Handling — proqramda yaranan xətaların idarə olunmasıdır ki, proqram qəfil dayanmadan, gözlənilməz hallarla mübarizə apararaq işləməyə davam etsin.

- `try` bloku istifadəçinin daxil etdiyi yaşı tam ədədə çevirməyə çalışır.  
- Əgər istifadəçi rəqəm daxil etməzsə, `ValueError` tutularaq uyğun xəta mesajı göstərilir.  
- `except Exception` bloku digər gözlənilməz xətaları tutub ekrana çıxarır.  
- `finally` bloku hər zaman işləyir və icranın tamamlandığını bildirir.  
- Bu struktur proqramın xətalara qarşı dayanıqlı işləməsini təmin edir.


In [62]:
try:
    # İstifadəçidən yaşını rəqəm olaraq daxil etməsini istəyir
    yaş = int(input("Yaşınızı daxil edin: "))
    # Daxil edilmiş yaşı çap edir
    print(f"Sizin yaşınız {yaş}-dir")

except ValueError:
    # Əgər daxil edilən dəyər tam ədəd deyilirsə, bu blok işə düşür
    print("Xəta: Yaş rəqəm olmalıdır!")

except Exception as e:
    # Digər bütün gözlənilməz xətaları tutub mesaj çap edir
    print(f"Gözlənilməz xəta: {e}")

finally:
    # Hər halda işləyəcək, icranın tamamlandığını bildirir
    print("İcra tamamlandı")

Yaşınızı daxil edin:  


Xəta: Yaş rəqəm olmalıdır!
İcra tamamlandı


- `BalXətası` adlı xüsusi xəta sinfi yaradılır və `Exception` sinifindən törəyir.  
- `bal_yoxla` funksiyası daxil edilən `bal` dəyərinin 0 ilə 100 arasında olub-olmadığını yoxlayır.  
- Əgər bal bu aralıqda deyilsə, `BalXətası` xətası `raise` ilə atılır və mesaj verilir.  
- Əks halda, bal dəyişəni funksiyadan geri qaytarılır.  
- Bu, balın düzgün diapazonda olub-olmadığını yoxlamaq üçün istifadə olunur.

In [63]:
class BalXətası(Exception):
    """Bal üçün xüsusi xəta sinfi"""
    pass

def bal_yoxla(bal):
    if bal < 0 or bal > 100:
        raise BalXətası("Bal 0-100 aralığında olmalıdır")
    return bal

- `try` blokunda əvvəlcə `bal_yoxla(85)` çağırılır və normal olaraq 85 çap olunur.  
- Sonra `bal_yoxla(120)` çağırılır, bu isə 0-100 aralığında olmadığı üçün `BalXətası` xətası atır.  
- `except BalXətası as e:` bloku bu xüsusi xətanı tutur və `e` vasitəsilə xəta mesajını çap edir.  
- Beləliklə, xəta proqramın dayanmasına səbəb olmadan idarə olunur.  
- Bu, öz xüsusi xətalarımızı yaratmaq və onları idarə etmək üçün istifadə olunan nümunədir.  

In [64]:
try:
    print(bal_yoxla(85))  # Normal
    print(bal_yoxla(120)) # Xəta
except BalXətası as e:
    print(f"Xəta: {e}")

85
Xəta: Bal 0-100 aralığında olmalıdır


## Generator-lar (Generators)

Generator — böyük verilənlər üzərində tək-tək elementləri yaddaşda saxlamadan, lazım olduqca istehsal edən xüsusi funksiyalardır. Bu, yaddaşa qənaət və performans üçün çox faydalıdır.

- `say_üstlü` funksiyası generator funksiyasıdır və `n`-ə qədər ədədlərin kvadratlarını istehsal edir.  
- `for i in range(n):` dövrü `0`-dan `n-1`-ə qədər ədədləri götürür.  
- `yield i ** 2` hər addımda `i`-nin kvadratını qaytarır, ancaq funksiyanı tamamilə dayandırmır.  
- Generatorlar yaddaşdan qənaətlə istifadə edir və böyük məlumatlar üzərində işləmək üçün əlverişlidir.  
- Bu funksiya çağırıldıqda generator obyekti qaytarır, onu dövr və ya `next()` ilə istifadə etmək olar.  

In [65]:
def say_üstlü(n):
    """Sayğac generatoru"""
    for i in range(n):
        yield i ** 2  # yield generator yaradır

- `say_üstlü(5)` çağırışı generator obyekti yaradır və `generator` dəyişəninə təyin olunur.  
- `type(generator)` funksiyası bu obyektin tipini göstərir, yəni `<class 'generator'>`.  
- Generator obyektləri iterator kimi işləyir və lazım olduqda dəyər istehsal edir.  
- Generatorlar yaddaşda böyük siyahılar yaratmadan təkrarlamağa imkan verir.  
- Bu obyekt `for` dövründə və ya `next()` funksiyası ilə istifadə oluna bilər.  


In [66]:
generator = say_üstlü(5)
print("Generator tipi:", type(generator))

Generator tipi: <class 'generator'>


- `for` dövrü ilə generator obyekti üzərində iterasiya edilir.  
- Hər iterasiyada `say_üstlü` funksiyasındakı `yield` ifadəsi növbəti kvadrat dəyəri qaytarır.  
- Generator yaddaşda tam siyahı saxlamır, hər dəfə tək-tək dəyərləri istehsal edir.  
- Dövr nəticəsində 0, 1, 4, 9, 16 çap olunur.  
- Generatorlar yaddaşa qənaət etməklə böyük verilənlər üzərində işləmək üçün faydalıdır.  

In [67]:
print("Generator dəyərləri:")
for dəyər in generator:
    print(dəyər)

Generator dəyərləri:
0
1
4
9
16


In [69]:
import sys

- `for` dövrü ilə generator obyekti üzərində iterasiya edilir.  
- Hər iterasiyada `say_üstlü` funksiyasındakı `yield` ifadəsi növbəti kvadrat dəyəri qaytarır.  
- Generator yaddaşda tam siyahı saxlamır, hər dəfə tək-tək dəyərləri istehsal edir.  
- Dövr nəticəsində 0, 1, 4, 9, 16 çap olunur.  
- Generatorlar yaddaşa qənaət etməklə böyük verilənlər üzərində işləmək üçün faydalıdır.


In [70]:
list_rəqəmlər = [x for x in range(100000)]
print("List yaddaş ölçüsü:", sys.getsizeof(list_rəqəmlər), "bayt")

# Generator yaratmaq
generator_rəqəmlər = (x for x in range(100000))
print("Generator yaddaş ölçüsü:", sys.getsizeof(generator_rəqəmlər), "bayt")

List yaddaş ölçüsü: 800984 bayt
Generator yaddaş ölçüsü: 192 bayt


Python-da yield açar sözü return kimi işləyir, amma tam fərqli davranır:

return funksiyanı bitirir və bir dəyər qaytarır.

yield isə dəyər qaytarır, amma funksiyanı dayandırmır — növbəti dəfə çağırıldıqda kaldığı yerdən davam edir.

In [71]:
def sayğac():
    """Dayandırıla bilən sayğac generatoru"""
    say = 0
    while True:
        yield say
        say += 1

iterator qurulur

In [72]:
counter = sayğac()

# Bir neçə dəyər almaq
print("\nSayğac dəyərləri:")
print(next(counter))  # 0
print(next(counter))  # 1
print(next(counter))  # 2



Sayğac dəyərləri:
0
1
2


- `orta_hesablayıcı()` funksiyası bir generator funksiyasıdır və `yield` ifadəsi ilə həm dəyər qəbul edir, həm də nəticə qaytarır.
- `next(ortalama)` generatoru işə salır və `yield` sətrinə qədər icra olunur.
- `send()` metodu ilə generatora dəyərlər göndərilir (10, 20, 30).
- Dəyərlər daxil olduqca `cəm` və `say` dəyişənləri yenilənir.
- `None` göndərildikdə dövr `break` ilə bitir və son `yield` ortalama dəyəri qaytarır.
- `StopIteration` istisnasının `value` atributu vasitəsilə nəticə əldə olunur.
- Nəticə olaraq 20.0 çap olunur.


In [74]:
def orta_hesablayıcı():
    """Dəyər qəbul edən generator"""
    cəm = 0
    say = 0
    while True:
        dəyər = yield  # yield dəyər qəbul edir
        if dəyər is None:
            break
        cəm += dəyər
        say += 1
    yield cəm / say if say > 0 else 0

# İstifadə
ortalama = orta_hesablayıcı()
next(ortalama)  # Generatoru başlatmaq

ortalama.send(10)  # Dəyər göndərmək
ortalama.send(20)
ortalama.send(30)

try:
    ortalama.send(None)  # Dayandırmaq üçün
except StopIteration as e:
    print("\nOrta dəyər:", e.value)  # 20.0

# NumPy və Pandas Kitabxanalarına Giriş

In [46]:
%pip install numpy  # Numpy kitabxanasını quraşdırır (data analizi və riyazi əməliyyatlar üçün)

Note: you may need to restart the kernel to use updated packages.


**NumPy** — riyazi və elmi hesablama üçün istifadə olunan məşhur bir Python kitabxanasıdır.  
**`np.array()`** funksiyası ilə **1 ölçülü bir massiv** (array) yaradılır.  
Bu massivdə **5 ədəd** var: `[1, 2, 3, 4, 5]`.  
**`print()`** funksiyası ilə massiv və onun **ölçüsü** ekrana çıxarılır.  
**`.shape`** — massivin neçə ölçülü və neçə elementli olduğunu göstərir.


In [5]:
import numpy as np

# 1D array yaratmaq
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)
print("Ölçü:", arr1d.shape)

1D Array:
[1 2 3 4 5]
Ölçü: (5,)


In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2d)
print("Ölçü:", arr2d.shape)


2D Array:
[[1 2 3]
 [4 5 6]]
Ölçü: (2, 3)


**`np.zeros((3, 3))`** funksiyası ilə **3x3 ölçülü** və **bütün elementləri 0 olan** bir array yaradılır.  
**`np.ones((2, 4))`** funksiyası **2x4 ölçülü** və **bütün elementləri 1 olan** bir array yaradır.  
**`np.arange(0, 10, 2)`** funksiyası ilə **0-dan 10-a qədər 2 vahidlik artımla** ardıcıl ədədlər alınır: `[0 2 4 6 8]`.  
**`np.random.rand(3, 3)`** funksiyası **3x3 ölçülü**, **0 ilə 1 arasında təsadüfi ədədlərdən ibarət** array yaradır.  
**`print()`** funksiyası ilə bütün bu arraylər səliqəli şəkildə ekrana çıxarılır.


In [3]:
# 3x3 ölçüdə bütün elementləri 0 olan array yaradır
zeros_arr = np.zeros((3, 3))

# 2x4 ölçüdə bütün elementləri 1 olan array yaradır
ones_arr = np.ones((2, 4))

# 0-dan 10-a qədər 2 addımla ardıcıl ədədlərdən ibarət array yaradır (0, 2, 4, 6, 8)
range_arr = np.arange(0, 10, 2)  # 0-dan 10-a qədər 2 addımla

# 3x3 ölçüdə 0 ilə 1 arasında təsadüfi ədədlərdən ibarət array yaradır
random_arr = np.random.rand(3, 3)  # 0-1 arası random ədədlər

# Nəticələrin çap olunması
print("\nXüsusi Arraylər:")  # Başlıq çap edir
print("Zeros:\n", zeros_arr)  # 0-lardan ibarət arrayi çap edir
print("Ones:\n", ones_arr)    # 1-lərdən ibarət arrayi çap edir
print("Arange:", range_arr)   # Ardıcıllığı çap edir
print("Random:\n", random_arr)  # Random ədədlərdən ibarət arrayi çap edir



Xüsusi Arraylər:
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Arange: [0 2 4 6 8]
Random:
 [[0.39063779 0.36104106 0.1015619 ]
 [0.33025401 0.89911428 0.72084756]
 [0.91774524 0.29058706 0.59117338]]


**`a` və `b`** adlı iki 1 ölçülü array yaradılır.  
**`a + b`** və **`a * b`** əməliyyatları ilə uyğun elementlər arasında toplama və vurma aparılır.  
**`np.dot(a, b)`** funksiyası ilə **nöqtə hasil** (dot product) hesablanır.  
**Universal funksiyalar** (ufuncs) — `np.sin()`, `np.exp()`, `np.sqrt()` — hər bir elementə ayrıca tətbiq olunur.  
Bu funksiyalarla **sinus**, **eksponent** və **kvadrat kök** kimi riyazi əməliyyatlar aparılır.


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Əsas riyazi əməliyyatlar
print("Toplama:", a + b)
print("Vurma:", a * b)  # Element-wise vurma
print("Nöqtə hasil:", np.dot(a, b))  # Dot product - bununla iki vektoru bir birine asanliqla vurmaq olar

# Universal funksiyalar (ufuncs)
print("Sinus:", np.sin(a))
print("Eksponent:", np.exp(a))
print("Kvadrat kök:", np.sqrt(a))

Toplama: [5 7 9]
Vurma: [ 4 10 18]
Nöqtə hasil: 32
Sinus: [0.84147098 0.90929743 0.14112001]
Eksponent: [ 2.71828183  7.3890561  20.08553692]
Kvadrat kök: [1.         1.41421356 1.73205081]


**3x3 ölçülü `arr` arrayi** yaradılır və içində 1-dən 9-a qədər ədədlər yerləşir.  
**`arr[0]`** ilə **ilk sətir**, **`arr[:, -1]`** ilə **son sütun** seçilir.  
**`arr[1, 1]`** ilə **ortadakı element** (5) alınır.  
**`arr[:2, 1:]`** ifadəsi ilə **ilk iki sətrin son iki sütunu** seçilərək **sub-array** yaradılır.  
**Boolean indexing** ilə **5-dən böyük olan elementlər** ayrıca süzülüb göstərilir.




In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Orijinal Array:\n", arr)
print("İlk sətir:", arr[0])
print("Son sütun:", arr[:, -1])
print("Orta element:", arr[1, 1])
print("Sub-array:\n", arr[:2, 1:])

# Boolean indexing
print("\nBoolean Indexing:")
print(arr[arr > 5])

Orijinal Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
İlk sətir: [1 2 3]
Son sütun: [3 6 9]
Orta element: 5
Sub-array:
 [[2 3]
 [5 6]]

Boolean Indexing:
[6 7 8 9]


**`np.arange(1, 10)`** funksiyası ilə 1-dən 9-a qədər ədədlərdən ibarət array yaradılır.  
**`reshape(3, 3)`** ilə bu array **3x3 ölçülü kvadrat formaya** salınır.  
**`flatten()`** funksiyası ilə array **yenidən 1 ölçülü** formaya gətirilir.  
**`T`** atributu ilə arrayin **transpozu** alınır, yəni sətir və sütunlar yer dəyişir.  
Bu əməliyyatlar massivlərin formasını dəyişmək üçün istifadə olunur.


In [6]:
arr = np.arange(1, 10)
print("Orijinal:", arr)

# Yenidən şəkilləndirmə
reshaped = arr.reshape(3, 3)
print("\nYenidən şəkilləndirilmiş:\n", reshaped)

# Düzəltmə
flattened = reshaped.flatten()
print("Düzəldilmiş:", flattened)

# Transpoz
transposed = reshaped.T
print("Transpoz:\n", transposed)

Orijinal: [1 2 3 4 5 6 7 8 9]

Yenidən şəkilləndirilmiş:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Düzəldilmiş: [1 2 3 4 5 6 7 8 9]
Transpoz:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


**`np.random.randint(1, 100, size=(5, 5))`** ilə **5x5 ölçüdə**, 1-dən 100-ə qədər **təsadüfi tam ədədlərdən ibarət** massiv yaradılır.  
**`np.mean()`, `np.median()`, `np.std()`** funksiyaları massiv üçün **orta**, **median** və **standart sapma** hesablayır.  
**`np.min()` və `np.max()`** massivdəki **ən kiçik və ən böyük** ədədləri tapır.  
**`np.sum(data, axis=0)`** sütunların cəmini,  
**`np.mean(data, axis=1)`** isə sətirlərin ortalamasını hesablayır.  
Bu funksiyalar verilənlər haqqında əsas statistik məlumat verir.


In [7]:
# 5x5 ölçüdə 1 ilə 100 arasında təsadüfi tam ədədlərdən ibarət array yaradır
data = np.random.randint(1, 100, size=(5, 5))


print("Data:\n", data)
print("\nStatistikalar:")
print("Orta:", np.mean(data))
print("Median:", np.median(data))
print("Standart sapma:", np.std(data))
print("Minimum:", np.min(data))
print("Maksimum:", np.max(data))
print("Sütun cəmi:", np.sum(data, axis=0))
print("Sətir ortası:", np.mean(data, axis=1))

Data:
 [[15 68 67 39 39]
 [17 60 56 86 98]
 [68 82  7 94 48]
 [ 7 29 48 58 25]
 [42 45 97 95 21]]

Statistikalar:
Orta: 52.44
Median: 48.0
Standart sapma: 28.312654414589954
Minimum: 7
Maksimum: 98
Sütun cəmi: [149 284 275 372 231]
Sətir ortası: [45.6 63.4 59.8 33.4 60. ]


In [6]:
# 3x3 array və 1D array (broadcast ediləcək)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([10, 20, 30])

# 3x3 array-ə 1x3 vektoru əlavə etmək
result = arr + vector
print("Broadcasting nəticəsi:\n", result)

Broadcasting nəticəsi:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [7]:
# Fancy indexing ilə müəyyən elementləri seçmək
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]  # 0, 2 və 4-cü elementləri seçirik

selected = arr[indices]
print("Fancy Indexing nəticəsi:", selected)

Fancy Indexing nəticəsi: [10 30 50]


In [8]:
# Masklama: 30-dan kiçik olanları 0 ilə əvəz et
arr = np.array([10, 25, 35, 50])
arr[arr < 30] = 0
print("Masklama və dəyişdirmə:", arr)

Masklama və dəyişdirmə: [ 0  0 35 50]


**`a` və `b` adlı 2x2 ölçülü iki array yaradılır.**  
**`np.vstack()`** funksiyası ilə bu iki array **dikey (şaquli) şəkildə birləşdirilir.**  
**`np.hstack()`** funksiyası ilə isə arraylər **üfüqi (horizontal) istiqamətdə birləşdirilir.**  
**`np.split()`** funksiyası ilə **üfüqi birləşdirilmiş array iki hissəyə bölünür.**  
Bu əməliyyatlar massivlərin birləşdirilməsi və bölünməsi üçün istifadə olunur.


In [9]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Dikey (vertical) birləşdirmə
vstacked = np.vstack((a, b))
print("Vertical Stack:\n", vstacked)

# Üfüqi (horizontal) birləşdirmə
hstacked = np.hstack((a, b))
print("Horizontal Stack:\n", hstacked)

# Split (2 hissəyə bölmək)
split_arr = np.split(hstacked, 2, axis=1)
print("Split nəticəsi:\n", split_arr[0], "\n", split_arr[1])

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Split nəticəsi:
 [[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]


**`matrix` adlı 2x2 ölçülü matriks yaradılır.**  
**`np.linalg.det()`** funksiyası ilə bu matriksin **determinantı** hesablanır.  
Determinant, matriksin tərsinin olub-olmamasını göstərir.  
**`np.linalg.inv()`** funksiyası matriksin **əksini (inversini)** tapır.  
Əgər determinant sıfır deyilsə, matriksin tərsi mövcuddur.


In [10]:
matrix = np.array([[4, 7], [2, 6]])

# Determinant
det = np.linalg.det(matrix)
print("Determinant:", det)

# İnvers (əks matriks)
inverse = np.linalg.inv(matrix)
print("Inverse:\n", inverse)

Determinant: 10.000000000000002
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


**`arr` adlı 1 ölçülü array yaradılır.**  
**`argmax()`** funksiyası arraydəki **ən böyük elementin indeksini** tapır.  
**`argmin()`** funksiyası isə **ən kiçik elementin indeksini** tapır.  
İndeks massivdə elementlərin sırasını göstərir, 0-dan başlayır.  
Bu funksiyalar massivdə maksimum və minimum dəyərlərin yerini tapmaq üçün faydalıdır.



In [11]:
arr = np.array([10, 50, 30, 70, 20])

# Ən böyük və ən kiçik elementlərin indeksləri
print("Ən böyük indeks (argmax):", arr.argmax())
print("Ən kiçik indeks (argmin):", arr.argmin())

Ən böyük indeks (argmax): 3
Ən kiçik indeks (argmin): 0


In [12]:
arr = np.array([3, 1, 2, 3, 2, 1, 4])

# Unikal elementlər və sıralama
print("Unique:", np.unique(arr))
print("Sort:", np.sort(arr))

Unique: [1 2 3 4]
Sort: [1 1 2 2 3 3 4]


**`arr` adlı 1 ölçülü array yaradılır.**  
**`np.clip(arr, 10, 30)`** funksiyası ilə **10-dan kiçik dəyərlər 10-a, 30-dan böyük dəyərlər 30-a çevrilir.**  
**`np.where(arr > 20, "Böyük", "Kiçik və ya bərabər")`** şərt əsasında **elementlərə uyğun sözlər təyin edir.**  
Bu üsul **şərtə görə seçim** və **dəyərlərin sərhədlər daxilində məhdudlaşdırılması** üçün istifadə olunur.  
Nəticələr yeni massiv şəklində göstərilir.


In [16]:
arr = np.array([5, 15, 25, 35])

# Clip: 10-dan kiçikləri 10, 30-dan böyük olanları 30 edir
clipped = np.clip(arr, 10, 30)
print("Clip nəticəsi:", clipped)

# Where: şərtə görə seçim
result = np.where(arr > 20, "Böyük", "Kiçik və ya bərabər")
print("Where nəticəsi:", result)

Clip nəticəsi: [10 15 25 30]
Where nəticəsi: ['Kiçik və ya bərabər' 'Kiçik və ya bərabər' 'Böyük' 'Böyük']


**`arr` adlı arraydə `np.nan` dəyərləri — yəni boş və ya naməlum ədədlər — yerləşdirilir.**  
**`np.isnan(arr)`** funksiyası ilə arraydə **NaN (Not a Number)** dəyərlərin olub-olmadığı yoxlanılır.  
**`np.nan_to_num(arr, nan=0)`** funksiyası ilə bütün **NaN-lar 0 ilə əvəz olunur.**  
Bu üsul **verilənlərdə boşluqları təmizləmək və hesablamalara hazır hala gətirmək** üçün istifadə olunur.  
Nəticədə təmizlənmiş array alınır.


In [17]:
arr = np.array([1, np.nan, 3, np.nan, 5])

# Nan-ların olub olmadığını yoxla
print("Nan varmı?:", np.isnan(arr))

# Nan-ları 0 ilə əvəz et
cleaned = np.nan_to_num(arr, nan=0)
print("Nan əvəz edilmiş:", cleaned)

Nan varmı?: [False  True False  True False]
Nan əvəz edilmiş: [1. 0. 3. 0. 5.]


**`np.random.seed(42)`** funksiyası, **hər dəfə eyni təsadüfi nəticələrin alınması üçün** istifadə olunur.  
Bu, **təkrar istehsal edilə bilən nəticələr** əldə etmək üçün vacibdir, xüsusilə test və analiz məqsədləri ilə.

Daha sonra **`np.random.randint(1, 100, 5)`** ilə 1-dən 100-ə qədər (100 daxil deyil) **5 ədəd təsadüfi tam ədəd** yaradılır.  
Seed təyin olunduğu üçün bu ədədlər **hər çalışmada eyni** olacaq.


In [18]:
np.random.seed(42)  # Hər dəfə eyni random nəticələr üçün
print("Random seed ilə:", np.random.randint(1, 100, 5))

Random seed ilə: [52 93 15 72 61]


## 2. Pandas Kitabxanası

In [13]:
%pip install pandas #pandas downloading

Note: you may need to restart the kernel to use updated packages.


- **pandas** kitabxanası `**pd**` qısaltması ilə import olunur.  
- **`data` adlı sözlük** yaradılır və burada ad, yaş və şəhər məlumatları saxlanılır.  
- Bu sözlük **`pd.DataFrame()`** funksiyası ilə **DataFrame**-ə çevrilir.  
- Yaradılan DataFrame **`df` dəyişənində** saxlanılır.  
- Sonda **`print(df)`** əmri ilə bu məlumatlar **ekrana çap olunur**.


In [20]:
# pandas kitabxanasını pd qısaltması ilə import edir
import pandas as pd

# Dictionary-dən DataFrame yaratmaq üçün nümunə məlumatlar
data = {
    'Ad': ['Əli', 'Aygün', 'Vaqif', 'Günay'],  # Adlar siyahısı
    'Yaş': [25, 30, 35, 28],                   # Müvafiq yaşlar
    'Şəhər': ['Bakı', 'Gəncə', 'Sumqayıt', 'Bakı']  # Müvafiq şəhərlər
}

# pandas DataFrame obyektinə çevirmək
df = pd.DataFrame(data)

# Yaradılmış DataFrame-i çap etmək
print("DataFrame:")
print(df)


DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Bakı


**İlk 2 sətrin göstərilməsi** üçün `df.head(2)` funksiyası istifadə olunur.  
**Təsviri statistika** üçün `df.describe()` funksiyası istifadə edilir və ədədi sütunların statistik göstəricilərini verir.  
**Sütun adlarını** görmək üçün `df.columns` istifadə olunur.  
`df['Yaş']` kodu ilə **yalnız "Yaş" sütunundakı məlumatlar** çıxarılır.  
`df[df['Yaş'] > 26]` ilə **yaşı 26-dan böyük olan şəxslər** süzülür.


In [15]:
print("\nƏsas Əməliyyatlar:")
print("İlk 2 sətir:\n", df.head(2))
print("\nTəsviri statistika:\n", df.describe())
print("\nSütunlar:", df.columns)
print("\nYaş sütunu:\n", df['Yaş'])
print("\nYaş > 26 olanlar:\n", df[df['Yaş'] > 26])


Əsas Əməliyyatlar:
İlk 2 sətir:
       Ad  Yaş  Şəhər
0    Əli   25   Bakı
1  Aygün   30  Gəncə

Təsviri statistika:
              Yaş
count   4.000000
mean   29.500000
std     4.203173
min    25.000000
25%    27.250000
50%    29.000000
75%    31.250000
max    35.000000

Sütunlar: Index(['Ad', 'Yaş', 'Şəhər'], dtype='object')

Yaş sütunu:
 0    25
1    30
2    35
3    28
Name: Yaş, dtype: int64

Yaş > 26 olanlar:
       Ad  Yaş     Şəhər
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Bakı


**`df.groupby('Şəhər')['Yaş'].mean()`** ilə **şəhərə görə yaşların orta qiyməti** hesablanır.  
Bu, məlumatları **qruplaşdırıb** hər qrup üçün statistik göstərici çıxarmağa imkan verir.  
**`pd.pivot_table()`** funksiyası ilə **pivot cədvəl** yaradılır, burada şəhər üzrə yaşların orta qiyməti göstərilir.  
Pivot cədvəl, məlumatları daha rahat və strukturlaşmış formada təqdim etmək üçün istifadə olunur.  
Qeyd: `value_counts()` funksiyası ilə müəyyən sütundakı unikal dəyərlərin sayını hesablamaq olar (şərhə alınmışdır).


In [11]:
print("\nQruplama Əməliyyatları:")
print("Şəhərə görə orta yaş:\n", df.groupby('Şəhər')['Yaş'].mean())
# print("\nTəhsilə görə say:\n", df['Təhsil'].value_counts())

# Pivot cədvəl
print("\nPivot Cədvəl:")
print(pd.pivot_table(df, values='Yaş', index='Şəhər', aggfunc='mean'))


Qruplama Əməliyyatları:
Şəhərə görə orta yaş:
 Şəhər
Bakı        26.5
Gəncə       30.0
Sumqayıt    35.0
Name: Yaş, dtype: float64

Pivot Cədvəl:
           Yaş
Şəhər         
Bakı      26.5
Gəncə     30.0
Sumqayıt  35.0


**`df.loc[1, 'Yaş'] = None`** ilə 1-ci sətrin **"Yaş" sütunundakı dəyər boş (None)** olaraq dəyişdirilir.  
**`df.loc[3, 'Şəhər'] = None`** ilə 3-cü sətrin **"Şəhər" sütunundakı dəyər boş (None)** olur.  
Bu əməliyyatlar DataFrame-də **məlumatların itirilməsi və ya boş qalması** vəziyyətini yaradır.  
**`print(df)`** ilə boşluqlar daxil olmaqla DataFrame ekrana çıxarılır.  
Boş dəyərlər analiz və məlumat təmizləmə mərhələsində vacib rol oynayır.


In [59]:
# 1-ci sətrin 'Yaş' sütunundakı dəyəri None (boş) olaraq dəyişdirir
df.loc[1, 'Yaş'] = None

# 3-cü sətrin 'Şəhər' sütunundakı dəyəri None (boş) olaraq dəyişdirir
df.loc[3, 'Şəhər'] = None

# Çatışmayan (boş) məlumatlar olan DataFrame-i çap edir
print("\nÇatışmayan məlumatlarla DataFrame:")
print(df)



Çatışmayan məlumatlarla DataFrame:
      Ad   Yaş     Şəhər
0    Əli  25.0      Bakı
1  Aygün   NaN     Gəncə
2  Vaqif  35.0  Sumqayıt
3  Günay  28.0      None


**`df.isnull()`** funksiyası DataFrame-də **boş (NaN) olan yerləri** `True`, olmayanları isə `False` kimi göstərir.  
**`.sum()`** metodu isə hər sütundakı **boş dəyərlərin sayını** toplayır.  


In [60]:
print("\nÇatışmayan məlumatların sayı:")
print(df.isnull().sum()) #null olan setirleri 1 digerlerini 0


Çatışmayan məlumatların sayı:
Ad       0
Yaş      1
Şəhər    1
dtype: int64


**`df.fillna()`** funksiyası DataFrame-dəki **boş (None/NaN) dəyərləri doldurmaq üçün istifadə olunur.**  
**`'Yaş'` sütunundakı boşluqlar həmin sütunun orta dəyəri ilə əvəz edilir.**  
**`'Şəhər'` sütunundakı boşluqlar isə "Naməlum" sözü ilə doldurulur.**  
Nəticədə, boşluqları aradan qaldıran **`filled_df` adlı yeni DataFrame** yaranır.  
**`print()`** funksiyası ilə doldurulmuş DataFrame ekrana çap olunur.


In [61]:
# Boş (None) olan dəyərləri doldurur:
# 'Yaş' sütunundakı boş dəyərləri həmin sütunun orta dəyəri ilə əvəz edir
# 'Şəhər' sütunundakı boş dəyərləri isə "Naməlum" sözü ilə əvəz edir
filled_df = df.fillna({'Yaş': df['Yaş'].mean(), 'Şəhər': 'Naməlum'})

# Doldurulmuş DataFrame-i çap edir
print("\nDoldurulmuş DataFrame:")
print(filled_df)



Doldurulmuş DataFrame:
      Ad        Yaş     Şəhər
0    Əli  25.000000      Bakı
1  Aygün  29.333333     Gəncə
2  Vaqif  35.000000  Sumqayıt
3  Günay  28.000000   Naməlum


In [62]:
df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})


**`pd.concat()` funksiyası ilə `df1` və `df2` DataFrame-ləri birləşdirilir.**  
**`ignore_index=True`** parametri ilə yeni yaranan DataFrame-in indeksləri sıfırdan başlayaraq yenidən qurulur.  
Bu, DataFrame-ləri ardıcıl şəkildə birləşdirmək üçün istifadə olunur.  
Nəticədə yaranan birləşdirilmiş DataFrame **`concat_df`** dəyişənində saxlanılır.  
**`print()`** ilə bu birləşmiş DataFrame ekranda göstərilir.


In [63]:
# df1 və df2 DataFrame-lərini birləşdirir və indeksləri sıfırdan yenidən düzür
concat_df = pd.concat([df1, df2], ignore_index=True)

# Birləşdirilmiş DataFrame-i çap edir
print("\nBirləşdirilmiş DataFrame:")
print(concat_df)



Birləşdirilmiş DataFrame:
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


**`left` adlı DataFrame `key` və `A` sütunlarından ibarətdir.**  
**`right` adlı DataFrame `key` və `B` sütunlarından ibarətdir.**  
**`pd.merge()` funksiyası ilə iki DataFrame `key` sütunu əsasında birləşdirilir (merge edilir).**  
Nəticədə hər iki DataFrame-dəki uyğun `key` dəyərləri birləşdirilərək yeni DataFrame yaranır.  
**`print()` funksiyası ilə bu birləşdirilmiş DataFrame ekrana çıxarılır.**


In [64]:
# Sol (left) DataFrame yaradır: 'key' və 'A' sütunları ilə
left = pd.DataFrame({'key': ['K0', 'K1'], 'A': ['A0', 'A1']})

# Sağ (right) DataFrame yaradır: 'key' və 'B' sütunları ilə
right = pd.DataFrame({'key': ['K0', 'K1'], 'B': ['B0', 'B1']})

# İki DataFrame-i 'key' sütunu üzrə birləşdirir (merge edir)
merged_df = pd.merge(left, right, on='key')

# Merge edilmiş (birləşdirilmiş) DataFrame-i çap edir
print("\nMerge edilmiş DataFrame:")
print(merged_df)


Merge edilmiş DataFrame:
  key   A   B
0  K0  A0  B0
1  K1  A1  B1


In [22]:
import pandas as pd

# Mövcud DataFrame
df = pd.DataFrame({
    'Ad': ['Əli', 'Aygün', 'Vaqif', 'Günay'],
    'Yaş': [25, 30, 35, 28],
    'Şəhər': ['Bakı', 'Gəncə', 'Sumqayıt', 'Şəki']
})

# Yeni sütun əlavə edir
df['Bal'] = [85, 90, 78, 92]
print("\nYeni sütun əlavə edilmiş DataFrame:")
print(df)

# Yeni sətir əlavə edir (pd.concat ilə)
new_row = pd.DataFrame([{'Ad': 'Murad', 'Yaş': 27, 'Şəhər': 'Lənkəran', 'Bal': 88}])
df = pd.concat([df, new_row], ignore_index=True)

print("\nYeni sətir əlavə edilmiş DataFrame:")
print(df)


Yeni sütun əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər  Bal
0    Əli   25      Bakı   85
1  Aygün   30     Gəncə   90
2  Vaqif   35  Sumqayıt   78
3  Günay   28      Şəki   92

Yeni sətir əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər  Bal
0    Əli   25      Bakı   85
1  Aygün   30     Gəncə   90
2  Vaqif   35  Sumqayıt   78
3  Günay   28      Şəki   92
4  Murad   27  Lənkəran   88


**`df.drop('Bal', axis=1)`** əmri ilə **`Bal` adlı sütun DataFrame-dən silinir.**  
`axis=1` parametri sütun əməliyyatı olduğunu göstərir.  
**`df.drop(2, axis=0)`** əmri ilə **2-ci indeksli sətir DataFrame-dən çıxarılır.**  
`axis=0` parametri sətir əməliyyatı olduğunu bildirir.  
Hər iki əməliyyatdan sonra dəyişmiş DataFrame `df` dəyişənində saxlanılır və çap olunur.


In [23]:
# 'Bal' sütununu silir
df = df.drop('Bal', axis=1)
print("\n'Bal' sütunu silinmiş DataFrame:")
print(df)

# 2-ci sətri silir
df = df.drop(2, axis=0)
print("\n2-ci sətri silinmiş DataFrame:")
print(df)


'Bal' sütunu silinmiş DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Şəki
4  Murad   27  Lənkəran

2-ci sətri silinmiş DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
3  Günay   28      Şəki
4  Murad   27  Lənkəran


**`df.sort_values(by='Yaş')`** ilə DataFrame **"Yaş" sütununa görə artan sırada** düzülür.  
Nəticədə, yaşa görə sıralanmış yeni DataFrame `sorted_df` dəyişənində saxlanılır.  
**`df.sort_index(ascending=False)`** ilə DataFrame **indeksə görə azalan sırada** düzülür.  
Bu, sətirlərin orijinal indekslərinə əsaslanaraq sıralama aparır.  
Hər iki nəticə `print()` funksiyası ilə ekrana çıxarılır.



In [24]:
# Yaşa görə artan sıralama
sorted_df = df.sort_values(by='Yaş')
print("\nYaşa görə sıralanmış DataFrame:")
print(sorted_df)

# İndekslərə görə azalan sıralama
sorted_index = df.sort_index(ascending=False)
print("\nİndeksə görə azalan sıralama:")
print(sorted_index)


Yaşa görə sıralanmış DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
4  Murad   27  Lənkəran
3  Günay   28      Şəki
1  Aygün   30     Gəncə

İndeksə görə azalan sıralama:
      Ad  Yaş     Şəhər
4  Murad   27  Lənkəran
3  Günay   28      Şəki
1  Aygün   30     Gəncə
0    Əli   25      Bakı


`df['Şəhər']` sütunundakı "Bakı" dəyəri **replace** funksiyası ilə "Baku" ilə dəyişdirilir.  
Dəyişdirilmiş DataFrame `print()` ilə ekrana çıxarılır.  
`df.rename()` funksiyası ilə "Yaş" sütununun adı **"Age"** olaraq dəyişdirilir.  
Yeni sütun adı ilə DataFrame `df` dəyişənində saxlanılır.  
Son olaraq dəyişikliklər ekrana çap olunur.


In [25]:
# Şəhər adlarını dəyişmək
df['Şəhər'] = df['Şəhər'].replace({'Bakı': 'Baku'})
print("\nDəyişdirilmiş Şəhər adları:")
print(df)

# Sütun adını dəyişmək
df = df.rename(columns={'Yaş': 'Age'})
print("\nSütun adı dəyişdirilmiş DataFrame:")
print(df)


Dəyişdirilmiş Şəhər adları:
      Ad  Yaş     Şəhər
0    Əli   25      Baku
1  Aygün   30     Gəncə
3  Günay   28      Şəki
4  Murad   27  Lənkəran

Sütun adı dəyişdirilmiş DataFrame:
      Ad  Age     Şəhər
0    Əli   25      Baku
1  Aygün   30     Gəncə
3  Günay   28      Şəki
4  Murad   27  Lənkəran


`df.set_index('Ad')` ilə **'Ad' sütunu indeks kimi təyin olunur.**  
Beləliklə, DataFrame-in sətrləri **adlarla identifikasiya edilir.**  
`print()` funksiyası ilə indeks təyin edilmiş DataFrame çap olunur.  
`df.reset_index()` ilə isə **indeks sıfırlanır** və əvvəlki sütunlar bərpa edilir.  
Nəticədə indeks yenidən sıradan başlayır və DataFrame çap olunur.


In [26]:
# 'Ad' sütununu indeks kimi təyin edir
df = df.set_index('Ad')
print("\n'Ad' indeks olaraq təyin edilmiş DataFrame:")
print(df)

# İndeksi sıfırlamaq
df = df.reset_index()
print("\nİndeks sıfırlanmış DataFrame:")
print(df)


'Ad' indeks olaraq təyin edilmiş DataFrame:
       Age     Şəhər
Ad                  
Əli     25      Baku
Aygün   30     Gəncə
Günay   28      Şəki
Murad   27  Lənkəran

İndeks sıfırlanmış DataFrame:
      Ad  Age     Şəhər
0    Əli   25      Baku
1  Aygün   30     Gəncə
2  Günay   28      Şəki
3  Murad   27  Lənkəran


In [29]:
import pandas as pd

# Nümunə DataFrame
df = pd.DataFrame({
    'Ad': ['Əli', 'Aygün', 'Vaqif', 'Günay'],
    'Yaş': [25, 30, 35, 28],
    'Şəhər': ['Bakı', 'Gəncə', 'Sumqayıt', 'Şəki']
})

# Dublikat sətir əlavə edir (pd.concat ilə)
df = pd.concat([df, df.iloc[[0]]], ignore_index=True)
print("\nDublikat əlavə edilmiş DataFrame:")
print(df)

# Dublikatları tapmaq
print("\nDublikatlar:")
print(df.duplicated())

# Dublikatları silmək
df = df.drop_duplicates()
print("\nDublikatları silmiş DataFrame:")
print(df)



Dublikat əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Şəki
4    Əli   25      Bakı

Dublikatlar:
0    False
1    False
2    False
3    False
4     True
dtype: bool

Dublikatları silmiş DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Şəki


`df['Şəhər'].str.upper()` ilə bütün şəhər adları **böyük hərflərə çevrilir.**  
Dəyişdirilmiş DataFrame `print()` ilə ekrana çıxarılır.  
`df['Şəhər'].str.contains('BAKU')` ilə **şəhər adı "BAKU" olan sətirlər seçilir.**  
Seçilmiş sətirlər ayrıca `print()` ilə göstərilir.  
Bu üsul mətn sütunlarında axtarış və filter tətbiq etmək üçün faydalıdır.


In [30]:
# Bütün şəhər adlarını böyük hərflərə çevirir
df['Şəhər'] = df['Şəhər'].str.upper()
print("\nBöyük hərflərlə şəhər adları:")
print(df)

# Şəhər adında 'BAKU' olanları seçmək
print("\n'BAKU' olan sətirlər:")
print(df[df['Şəhər'].str.contains('BAKU')])


Böyük hərflərlə şəhər adları:
      Ad  Yaş     Şəhər
0    Əli   25      BAKI
1  Aygün   30     GƏNCƏ
2  Vaqif   35  SUMQAYIT
3  Günay   28      ŞƏKI

'BAKU' olan sətirlər:
Empty DataFrame
Columns: [Ad, Yaş, Şəhər]
Index: []


`kateqoriya` adlı funksiya yaşa görə **"Gənc" və ya "Yetkin"** kateqoriyasını təyin edir.  
`df['Yaş'].apply(kateqoriya)` ilə funksiyanı hər yaş dəyərinə tətbiq edirik.  
Nəticə yeni **"Kateqoriya"** sütununa əlavə olunur.  
Dəyişdirilmiş DataFrame `print()` ilə ekrana çıxarılır.  
Bu üsul sütunlara xüsusi funksiyalar tətbiq etmək üçün geniş istifadə olunur.  


In [32]:
# Yaşa görə kateqoriya yaratmaq
def kateqoriya(yas):
    if yas < 30:
        return "Gənc"
    else:
        return "Yetkin"

df['Kateqoriya'] = df['Yaş'].apply(kateqoriya)
print("\napply ilə kateqoriya əlavə edilmiş DataFrame:")
print(df)



apply ilə kateqoriya əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər Kateqoriya
0    Əli   25      BAKI       Gənc
1  Aygün   30     GƏNCƏ     Yetkin
2  Vaqif   35  SUMQAYIT     Yetkin
3  Günay   28      ŞƏKI       Gənc


`df.to_csv('output.csv', index=False)` ilə DataFrame **'output.csv'** adlı CSV faylına yazılır.  
`index=False` indeksi fayla daxil etməmək üçündür.  
`pd.read_csv('output.csv')` funksiyası ilə həmin CSV faylı **yenidən oxunur** və DataFrame-ə çevrilir.  
Oxunan DataFrame `new_df` dəyişənində saxlanılır.  
`print()` ilə oxunan DataFrame ekrana çıxarılır.  


In [33]:
# DataFrame-i CSV faylına yazır
df.to_csv('output.csv', index=False)
print("\nDataFrame 'output.csv' faylına yazıldı")

# CSV faylını oxuyur
new_df = pd.read_csv('output.csv')
print("\nCSV-dən oxunan DataFrame:")
print(new_df)


DataFrame 'output.csv' faylına yazıldı

CSV-dən oxunan DataFrame:
      Ad  Yaş     Şəhər Kateqoriya
0    Əli   25      BAKI       Gənc
1  Aygün   30     GƏNCƏ     Yetkin
2  Vaqif   35  SUMQAYIT     Yetkin
3  Günay   28      ŞƏKI       Gənc


`df.copy()` ilə DataFrame-nin surəti yaradılır.  
`df_with_nan.loc[1, 'Age'] = None` ilə 1-ci sətrin "Age" sütununa boş dəyər əlavə olunur.  
`print()` ilə boş dəyər əlavə edilmiş DataFrame göstərilir.  
`df_with_nan.dropna()` funksiyası ilə **boş dəyərlər olan sətrlər silinir.**  
Təmizlənmiş DataFrame `cleaned_df` dəyişənində saxlanılır və ekrana çıxarılır.  


In [34]:
# Boş dəyərləri silir
df_with_nan = df.copy()
df_with_nan.loc[1, 'Age'] = None  # Boş dəyər əlavə edək
print("\nBoş dəyər əlavə edilmiş DataFrame:")
print(df_with_nan)

cleaned_df = df_with_nan.dropna()
print("\nBoş dəyərlər silinmiş DataFrame:")
print(cleaned_df)


Boş dəyər əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər Kateqoriya   Age
0    Əli   25      BAKI       Gənc   NaN
1  Aygün   30     GƏNCƏ     Yetkin  None
2  Vaqif   35  SUMQAYIT     Yetkin   NaN
3  Günay   28      ŞƏKI       Gənc   NaN

Boş dəyərlər silinmiş DataFrame:
Empty DataFrame
Columns: [Ad, Yaş, Şəhər, Kateqoriya, Age]
Index: []
