# NumPy və Pandas Kitabxanalarına Giriş

In [46]:
%pip install numpy  # Numpy kitabxanasını quraşdırır (data analizi və riyazi əməliyyatlar üçün)

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

# 1D array yaratmaq
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)
print("Ölçü:", arr1d.shape)

1D Array:
[1 2 3 4 5]
Ölçü: (5,)


In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2d)
print("Ölçü:", arr2d.shape)


2D Array:
[[1 2 3]
 [4 5 6]]
Ölçü: (2, 3)


In [3]:
# 3x3 ölçüdə bütün elementləri 0 olan array yaradır
zeros_arr = np.zeros((3, 3))

# 2x4 ölçüdə bütün elementləri 1 olan array yaradır
ones_arr = np.ones((2, 4))

# 0-dan 10-a qədər 2 addımla ardıcıl ədədlərdən ibarət array yaradır (0, 2, 4, 6, 8)
range_arr = np.arange(0, 10, 2)  # 0-dan 10-a qədər 2 addımla

# 3x3 ölçüdə 0 ilə 1 arasında təsadüfi ədədlərdən ibarət array yaradır
random_arr = np.random.rand(3, 3)  # 0-1 arası random ədədlər

# Nəticələrin çap olunması
print("\nXüsusi Arraylər:")  # Başlıq çap edir
print("Zeros:\n", zeros_arr)  # 0-lardan ibarət arrayi çap edir
print("Ones:\n", ones_arr)    # 1-lərdən ibarət arrayi çap edir
print("Arange:", range_arr)   # Ardıcıllığı çap edir
print("Random:\n", random_arr)  # Random ədədlərdən ibarət arrayi çap edir



Xüsusi Arraylər:
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Arange: [0 2 4 6 8]
Random:
 [[0.39063779 0.36104106 0.1015619 ]
 [0.33025401 0.89911428 0.72084756]
 [0.91774524 0.29058706 0.59117338]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Əsas riyazi əməliyyatlar
print("Toplama:", a + b)
print("Vurma:", a * b)  # Element-wise vurma
print("Nöqtə hasil:", np.dot(a, b))  # Dot product - bununla iki vektoru bir birine asanliqla vurmaq olar

# Universal funksiyalar (ufuncs)
print("Sinus:", np.sin(a))
print("Eksponent:", np.exp(a))
print("Kvadrat kök:", np.sqrt(a))

Toplama: [5 7 9]
Vurma: [ 4 10 18]
Nöqtə hasil: 32
Sinus: [0.84147098 0.90929743 0.14112001]
Eksponent: [ 2.71828183  7.3890561  20.08553692]
Kvadrat kök: [1.         1.41421356 1.73205081]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Orijinal Array:\n", arr)
print("İlk sətir:", arr[0])
print("Son sütun:", arr[:, -1])
print("Orta element:", arr[1, 1])
print("Sub-array:\n", arr[:2, 1:])

# Boolean indexing
print("\nBoolean Indexing:")
print(arr[arr > 5])

Orijinal Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
İlk sətir: [1 2 3]
Son sütun: [3 6 9]
Orta element: 5
Sub-array:
 [[2 3]
 [5 6]]

Boolean Indexing:
[6 7 8 9]


In [6]:
arr = np.arange(1, 10)
print("Orijinal:", arr)

# Yenidən şəkilləndirmə
reshaped = arr.reshape(3, 3)
print("\nYenidən şəkilləndirilmiş:\n", reshaped)

# Düzəltmə
flattened = reshaped.flatten()
print("Düzəldilmiş:", flattened)

# Transpoz
transposed = reshaped.T
print("Transpoz:\n", transposed)

Orijinal: [1 2 3 4 5 6 7 8 9]

Yenidən şəkilləndirilmiş:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Düzəldilmiş: [1 2 3 4 5 6 7 8 9]
Transpoz:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
# 5x5 ölçüdə 1 ilə 100 arasında təsadüfi tam ədədlərdən ibarət array yaradır
data = np.random.randint(1, 100, size=(5, 5))


print("Data:\n", data)b
print("\nStatistikalar:")
print("Orta:", np.mean(data))
print("Median:", np.median(data))
print("Standart sapma:", np.std(data))
print("Minimum:", np.min(data))
print("Maksimum:", np.max(data))
print("Sütun cəmi:", np.sum(data, axis=0))
print("Sətir ortası:", np.mean(data, axis=1))

Data:
 [[15 68 67 39 39]
 [17 60 56 86 98]
 [68 82  7 94 48]
 [ 7 29 48 58 25]
 [42 45 97 95 21]]

Statistikalar:
Orta: 52.44
Median: 48.0
Standart sapma: 28.312654414589954
Minimum: 7
Maksimum: 98
Sütun cəmi: [149 284 275 372 231]
Sətir ortası: [45.6 63.4 59.8 33.4 60. ]


In [6]:
# 3x3 array və 1D array (broadcast ediləcək)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([10, 20, 30])

# 3x3 array-ə 1x3 vektoru əlavə etmək
result = arr + vector
print("Broadcasting nəticəsi:\n", result)

Broadcasting nəticəsi:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [7]:
# Fancy indexing ilə müəyyən elementləri seçmək
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]  # 0, 2 və 4-cü elementləri seçirik

selected = arr[indices]
print("Fancy Indexing nəticəsi:", selected)

Fancy Indexing nəticəsi: [10 30 50]


In [8]:
# Masklama: 30-dan kiçik olanları 0 ilə əvəz et
arr = np.array([10, 25, 35, 50])
arr[arr < 30] = 0
print("Masklama və dəyişdirmə:", arr)

Masklama və dəyişdirmə: [ 0  0 35 50]


In [9]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Dikey (vertical) birləşdirmə
vstacked = np.vstack((a, b))
print("Vertical Stack:\n", vstacked)

# Üfüqi (horizontal) birləşdirmə
hstacked = np.hstack((a, b))
print("Horizontal Stack:\n", hstacked)

# Split (2 hissəyə bölmək)
split_arr = np.split(hstacked, 2, axis=1)
print("Split nəticəsi:\n", split_arr[0], "\n", split_arr[1])

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Split nəticəsi:
 [[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]


In [10]:
matrix = np.array([[4, 7], [2, 6]])

# Determinant
det = np.linalg.det(matrix)
print("Determinant:", det)

# İnvers (əks matriks)
inverse = np.linalg.inv(matrix)
print("Inverse:\n", inverse)

Determinant: 10.000000000000002
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [11]:
arr = np.array([10, 50, 30, 70, 20])

# Ən böyük və ən kiçik elementlərin indeksləri
print("Ən böyük indeks (argmax):", arr.argmax())
print("Ən kiçik indeks (argmin):", arr.argmin())

Ən böyük indeks (argmax): 3
Ən kiçik indeks (argmin): 0


In [12]:
arr = np.array([3, 1, 2, 3, 2, 1, 4])

# Unikal elementlər və sıralama
print("Unique:", np.unique(arr))
print("Sort:", np.sort(arr))

Unique: [1 2 3 4]
Sort: [1 1 2 2 3 3 4]


In [16]:
arr = np.array([5, 15, 25, 35])

# Clip: 10-dan kiçikləri 10, 30-dan böyük olanları 30 edir
clipped = np.clip(arr, 10, 30)
print("Clip nəticəsi:", clipped)

# Where: şərtə görə seçim
result = np.where(arr > 20, "Böyük", "Kiçik və ya bərabər")
print("Where nəticəsi:", result)

Clip nəticəsi: [10 15 25 30]
Where nəticəsi: ['Kiçik və ya bərabər' 'Kiçik və ya bərabər' 'Böyük' 'Böyük']


In [17]:
arr = np.array([1, np.nan, 3, np.nan, 5])

# Nan-ların olub olmadığını yoxla
print("Nan varmı?:", np.isnan(arr))

# Nan-ları 0 ilə əvəz et
cleaned = np.nan_to_num(arr, nan=0)
print("Nan əvəz edilmiş:", cleaned)

Nan varmı?: [False  True False  True False]
Nan əvəz edilmiş: [1. 0. 3. 0. 5.]


In [18]:
np.random.seed(42)  # Hər dəfə eyni random nəticələr üçün
print("Random seed ilə:", np.random.randint(1, 100, 5))

Random seed ilə: [52 93 15 72 61]


## 2. Pandas Kitabxanası

In [13]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [20]:
# pandas kitabxanasını pd qısaltması ilə import edir
import pandas as pd

# Dictionary-dən DataFrame yaratmaq üçün nümunə məlumatlar
data = {
    'Ad': ['Əli', 'Aygün', 'Vaqif', 'Günay'],  # Adlar siyahısı
    'Yaş': [25, 30, 35, 28],                   # Müvafiq yaşlar
    'Şəhər': ['Bakı', 'Gəncə', 'Sumqayıt', 'Bakı']  # Müvafiq şəhərlər
}

# pandas DataFrame obyektinə çevirmək
df = pd.DataFrame(data)

# Yaradılmış DataFrame-i çap etmək
print("DataFrame:")
print(df)


DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Bakı


In [15]:
print("\nƏsas Əməliyyatlar:")
print("İlk 2 sətir:\n", df.head(2))
print("\nTəsviri statistika:\n", df.describe())
print("\nSütunlar:", df.columns)
print("\nYaş sütunu:\n", df['Yaş'])
print("\nYaş > 26 olanlar:\n", df[df['Yaş'] > 26])


Əsas Əməliyyatlar:
İlk 2 sətir:
       Ad  Yaş  Şəhər
0    Əli   25   Bakı
1  Aygün   30  Gəncə

Təsviri statistika:
              Yaş
count   4.000000
mean   29.500000
std     4.203173
min    25.000000
25%    27.250000
50%    29.000000
75%    31.250000
max    35.000000

Sütunlar: Index(['Ad', 'Yaş', 'Şəhər'], dtype='object')

Yaş sütunu:
 0    25
1    30
2    35
3    28
Name: Yaş, dtype: int64

Yaş > 26 olanlar:
       Ad  Yaş     Şəhər
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Bakı


In [11]:
print("\nQruplama Əməliyyatları:")
print("Şəhərə görə orta yaş:\n", df.groupby('Şəhər')['Yaş'].mean())
# print("\nTəhsilə görə say:\n", df['Təhsil'].value_counts())

# Pivot cədvəl
print("\nPivot Cədvəl:")
print(pd.pivot_table(df, values='Yaş', index='Şəhər', aggfunc='mean'))


Qruplama Əməliyyatları:
Şəhərə görə orta yaş:
 Şəhər
Bakı        26.5
Gəncə       30.0
Sumqayıt    35.0
Name: Yaş, dtype: float64

Pivot Cədvəl:
           Yaş
Şəhər         
Bakı      26.5
Gəncə     30.0
Sumqayıt  35.0


In [59]:
# 1-ci sətrin 'Yaş' sütunundakı dəyəri None (boş) olaraq dəyişdirir
df.loc[1, 'Yaş'] = None

# 3-cü sətrin 'Şəhər' sütunundakı dəyəri None (boş) olaraq dəyişdirir
df.loc[3, 'Şəhər'] = None

# Çatışmayan (boş) məlumatlar olan DataFrame-i çap edir
print("\nÇatışmayan məlumatlarla DataFrame:")
print(df)



Çatışmayan məlumatlarla DataFrame:
      Ad   Yaş     Şəhər
0    Əli  25.0      Bakı
1  Aygün   NaN     Gəncə
2  Vaqif  35.0  Sumqayıt
3  Günay  28.0      None


In [60]:
print("\nÇatışmayan məlumatların sayı:")
print(df.isnull().sum()) #null olan setirleri 1 digerlerini 0


Çatışmayan məlumatların sayı:
Ad       0
Yaş      1
Şəhər    1
dtype: int64


In [61]:
# Boş (None) olan dəyərləri doldurur:
# 'Yaş' sütunundakı boş dəyərləri həmin sütunun orta dəyəri ilə əvəz edir
# 'Şəhər' sütunundakı boş dəyərləri isə "Naməlum" sözü ilə əvəz edir
filled_df = df.fillna({'Yaş': df['Yaş'].mean(), 'Şəhər': 'Naməlum'})

# Doldurulmuş DataFrame-i çap edir
print("\nDoldurulmuş DataFrame:")
print(filled_df)



Doldurulmuş DataFrame:
      Ad        Yaş     Şəhər
0    Əli  25.000000      Bakı
1  Aygün  29.333333     Gəncə
2  Vaqif  35.000000  Sumqayıt
3  Günay  28.000000   Naməlum


In [62]:
df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})


In [63]:
# df1 və df2 DataFrame-lərini birləşdirir və indeksləri sıfırdan yenidən düzür
concat_df = pd.concat([df1, df2], ignore_index=True)

# Birləşdirilmiş DataFrame-i çap edir
print("\nBirləşdirilmiş DataFrame:")
print(concat_df)



Birləşdirilmiş DataFrame:
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [64]:
# Sol (left) DataFrame yaradır: 'key' və 'A' sütunları ilə
left = pd.DataFrame({'key': ['K0', 'K1'], 'A': ['A0', 'A1']})

# Sağ (right) DataFrame yaradır: 'key' və 'B' sütunları ilə
right = pd.DataFrame({'key': ['K0', 'K1'], 'B': ['B0', 'B1']})

# İki DataFrame-i 'key' sütunu üzrə birləşdirir (merge edir)
merged_df = pd.merge(left, right, on='key')

# Merge edilmiş (birləşdirilmiş) DataFrame-i çap edir
print("\nMerge edilmiş DataFrame:")
print(merged_df)



Merge edilmiş DataFrame:
  key   A   B
0  K0  A0  B0
1  K1  A1  B1


In [22]:
import pandas as pd

# Mövcud DataFrame
df = pd.DataFrame({
    'Ad': ['Əli', 'Aygün', 'Vaqif', 'Günay'],
    'Yaş': [25, 30, 35, 28],
    'Şəhər': ['Bakı', 'Gəncə', 'Sumqayıt', 'Şəki']
})

# Yeni sütun əlavə edir
df['Bal'] = [85, 90, 78, 92]
print("\nYeni sütun əlavə edilmiş DataFrame:")
print(df)

# Yeni sətir əlavə edir (pd.concat ilə)
new_row = pd.DataFrame([{'Ad': 'Murad', 'Yaş': 27, 'Şəhər': 'Lənkəran', 'Bal': 88}])
df = pd.concat([df, new_row], ignore_index=True)

print("\nYeni sətir əlavə edilmiş DataFrame:")
print(df)


Yeni sütun əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər  Bal
0    Əli   25      Bakı   85
1  Aygün   30     Gəncə   90
2  Vaqif   35  Sumqayıt   78
3  Günay   28      Şəki   92

Yeni sətir əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər  Bal
0    Əli   25      Bakı   85
1  Aygün   30     Gəncə   90
2  Vaqif   35  Sumqayıt   78
3  Günay   28      Şəki   92
4  Murad   27  Lənkəran   88


In [23]:
# 'Bal' sütununu silir
df = df.drop('Bal', axis=1)
print("\n'Bal' sütunu silinmiş DataFrame:")
print(df)

# 2-ci sətri silir
df = df.drop(2, axis=0)
print("\n2-ci sətri silinmiş DataFrame:")
print(df)


'Bal' sütunu silinmiş DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Şəki
4  Murad   27  Lənkəran

2-ci sətri silinmiş DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
3  Günay   28      Şəki
4  Murad   27  Lənkəran


In [24]:
# Yaşa görə artan sıralama
sorted_df = df.sort_values(by='Yaş')
print("\nYaşa görə sıralanmış DataFrame:")
print(sorted_df)

# İndekslərə görə azalan sıralama
sorted_index = df.sort_index(ascending=False)
print("\nİndeksə görə azalan sıralama:")
print(sorted_index)


Yaşa görə sıralanmış DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
4  Murad   27  Lənkəran
3  Günay   28      Şəki
1  Aygün   30     Gəncə

İndeksə görə azalan sıralama:
      Ad  Yaş     Şəhər
4  Murad   27  Lənkəran
3  Günay   28      Şəki
1  Aygün   30     Gəncə
0    Əli   25      Bakı


In [25]:
# Şəhər adlarını dəyişmək
df['Şəhər'] = df['Şəhər'].replace({'Bakı': 'Baku'})
print("\nDəyişdirilmiş Şəhər adları:")
print(df)

# Sütun adını dəyişmək
df = df.rename(columns={'Yaş': 'Age'})
print("\nSütun adı dəyişdirilmiş DataFrame:")
print(df)


Dəyişdirilmiş Şəhər adları:
      Ad  Yaş     Şəhər
0    Əli   25      Baku
1  Aygün   30     Gəncə
3  Günay   28      Şəki
4  Murad   27  Lənkəran

Sütun adı dəyişdirilmiş DataFrame:
      Ad  Age     Şəhər
0    Əli   25      Baku
1  Aygün   30     Gəncə
3  Günay   28      Şəki
4  Murad   27  Lənkəran


In [26]:
# 'Ad' sütununu indeks kimi təyin edir
df = df.set_index('Ad')
print("\n'Ad' indeks olaraq təyin edilmiş DataFrame:")
print(df)

# İndeksi sıfırlamaq
df = df.reset_index()
print("\nİndeks sıfırlanmış DataFrame:")
print(df)


'Ad' indeks olaraq təyin edilmiş DataFrame:
       Age     Şəhər
Ad                  
Əli     25      Baku
Aygün   30     Gəncə
Günay   28      Şəki
Murad   27  Lənkəran

İndeks sıfırlanmış DataFrame:
      Ad  Age     Şəhər
0    Əli   25      Baku
1  Aygün   30     Gəncə
2  Günay   28      Şəki
3  Murad   27  Lənkəran


In [29]:
import pandas as pd

# Nümunə DataFrame
df = pd.DataFrame({
    'Ad': ['Əli', 'Aygün', 'Vaqif', 'Günay'],
    'Yaş': [25, 30, 35, 28],
    'Şəhər': ['Bakı', 'Gəncə', 'Sumqayıt', 'Şəki']
})

# Dublikat sətir əlavə edir (pd.concat ilə)
df = pd.concat([df, df.iloc[[0]]], ignore_index=True)
print("\nDublikat əlavə edilmiş DataFrame:")
print(df)

# Dublikatları tapmaq
print("\nDublikatlar:")
print(df.duplicated())

# Dublikatları silmək
df = df.drop_duplicates()
print("\nDublikatları silmiş DataFrame:")
print(df)



Dublikat əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Şəki
4    Əli   25      Bakı

Dublikatlar:
0    False
1    False
2    False
3    False
4     True
dtype: bool

Dublikatları silmiş DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Şəki


In [30]:
# Bütün şəhər adlarını böyük hərflərə çevirir
df['Şəhər'] = df['Şəhər'].str.upper()
print("\nBöyük hərflərlə şəhər adları:")
print(df)

# Şəhər adında 'BAKU' olanları seçmək
print("\n'BAKU' olan sətirlər:")
print(df[df['Şəhər'].str.contains('BAKU')])


Böyük hərflərlə şəhər adları:
      Ad  Yaş     Şəhər
0    Əli   25      BAKI
1  Aygün   30     GƏNCƏ
2  Vaqif   35  SUMQAYIT
3  Günay   28      ŞƏKI

'BAKU' olan sətirlər:
Empty DataFrame
Columns: [Ad, Yaş, Şəhər]
Index: []


In [32]:
# Yaşa görə kateqoriya yaratmaq
def kateqoriya(yas):
    if yas < 30:
        return "Gənc"
    else:
        return "Yetkin"

df['Kateqoriya'] = df['Yaş'].apply(kateqoriya)
print("\napply ilə kateqoriya əlavə edilmiş DataFrame:")
print(df)



apply ilə kateqoriya əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər Kateqoriya
0    Əli   25      BAKI       Gənc
1  Aygün   30     GƏNCƏ     Yetkin
2  Vaqif   35  SUMQAYIT     Yetkin
3  Günay   28      ŞƏKI       Gənc


In [33]:
# DataFrame-i CSV faylına yazır
df.to_csv('output.csv', index=False)
print("\nDataFrame 'output.csv' faylına yazıldı")

# CSV faylını oxuyur
new_df = pd.read_csv('output.csv')
print("\nCSV-dən oxunan DataFrame:")
print(new_df)



DataFrame 'output.csv' faylına yazıldı

CSV-dən oxunan DataFrame:
      Ad  Yaş     Şəhər Kateqoriya
0    Əli   25      BAKI       Gənc
1  Aygün   30     GƏNCƏ     Yetkin
2  Vaqif   35  SUMQAYIT     Yetkin
3  Günay   28      ŞƏKI       Gənc


In [34]:
# Boş dəyərləri silir
df_with_nan = df.copy()
df_with_nan.loc[1, 'Age'] = None  # Boş dəyər əlavə edək
print("\nBoş dəyər əlavə edilmiş DataFrame:")
print(df_with_nan)

cleaned_df = df_with_nan.dropna()
print("\nBoş dəyərlər silinmiş DataFrame:")
print(cleaned_df)


Boş dəyər əlavə edilmiş DataFrame:
      Ad  Yaş     Şəhər Kateqoriya   Age
0    Əli   25      BAKI       Gənc   NaN
1  Aygün   30     GƏNCƏ     Yetkin  None
2  Vaqif   35  SUMQAYIT     Yetkin   NaN
3  Günay   28      ŞƏKI       Gənc   NaN

Boş dəyərlər silinmiş DataFrame:
Empty DataFrame
Columns: [Ad, Yaş, Şəhər, Kateqoriya, Age]
Index: []


# Python Basics


### 1.1 Dəyişənlər və Operatorlar

## Əsas dəyişən tipləri

In [4]:
tam_ədəd = 42                  # int
kəsr_ədəd = 3.14               # float
mətn = "Salam, Dünya!"         # str
məntiqi = True                 # bool
heç_nə = None                  # NoneType

### Çoxsətirli mətn

In [5]:
çoxsətirli = """
Bu çoxsətirli
mətn nümunəsidir.
"""

In [7]:
print(çoxsətirli)


Bu çoxsətirli
mətn nümunəsidir.



In [8]:
çoxsətirli

'\nBu çoxsətirli\nmətn nümunəsidir.\n'

## Dinamik tip dəyişmə

In [10]:
dəyişən = 10
print(type(dəyişən))  # <class 'int'>
dəyişən = "on"
print(type(dəyişən))  # <class 'str'>


<class 'int'>
<class 'str'>


## Operatorlar nümunələri

In [11]:
a, b = 10, 3

print("Toplama:", a + b)       # 13
print("Çıxma:", a - b)         # 7
print("Vurma:", a * b)         # 30
print("Bölmə:", a / b)         # 3.333...
print("Tam bölmə:", a // b)    # 3
print("Qalıq:", a % b)         # 1
print("Üst:", a ** b)          # 1000


Toplama: 13
Çıxma: 7
Vurma: 30
Bölmə: 3.3333333333333335
Tam bölmə: 3
Qalıq: 1
Üst: 1000


## Müqayisə operatorları

In [12]:
print("a > b:", a > b)         # True
print("a == b:", a == b)       # False
print("a != b:", a != b)       # True

a > b: True
a == b: False
a != b: True


## Məntiqi operatorlar

In [13]:
print("AND:", True and False)  # False
print("OR:", True or False)    # True
print("NOT:", not True)        # False


AND: False
OR: True
NOT: False


# 1.2 Şərt İfadələri

In [15]:
bal = 85
#burda her zaman indentention gozlenmelidir yeni : den sonra asagi setirde bir tab ve ya 4 bosluq
if bal >= 90:
    print("Əla!")
elif bal >= 70:
    print("Yaxşı!")
elif bal >= 50:
    print("Qənaətbəxş")
else:
    print("Kəsildiniz")

Yaxşı!


### İç-içə şərtlər

In [3]:
yaş = 20
təhsil = "ali"

if yaş >= 18:
    if təhsil == "ali":
        print("İş üçün uyğunsunuz")
    else:
        print("Təhsil şərtinə uyğun deyilsiniz")
else:
    print("Yaş şərtinə uyğun deyilsiniz")

İş üçün uyğunsunuz


In [18]:
# İki ədəd təyin edir
x = 10
y = 20

# x və y arasından kiçik olanı seçir
# Əgər x < y-dirsə, kiçik = x olacaq, əks halda kiçik = y olacaq
kiçik = x if x < y else y

# Nəticəni çap edir
print("Kiçik olan:", kiçik)

Kiçik olan: 10


# 1.3 Dövrlər

In [20]:
# Ekrana "0-dan 4-ə qədər:" yazdırır
print("0-dan 4-ə qədər:")

# 0-dan başlayaraq 4-ə qədər (5 daxil deyil) ədədləri çap edir
for i in range(5):
    # i dəyərini boşluqla ayıraraq çap edir (new line olmadan)
    print(i, end=' ')


0-dan 4-ə qədər:
0 1 2 3 4 

In [21]:
print("\n\n5-dən 9-a qədər:")
for i in range(5, 10):
    print(i, end=' ')




5-dən 9-a qədər:
5 6 7 8 9 

In [22]:
print("\n\n0-dan 10-a qədər 2 addım:")
for i in range(0, 11, 2):
    print(i, end=' ')



0-dan 10-a qədər 2 addım:
0 2 4 6 8 10 

In [23]:
meyvələr = ["alma", "armud", "banan", "nar"]
print("\n\nMeyvələr siyahısı:")
for meyvə in meyvələr:
    print(meyvə.title())



Meyvələr siyahısı:
Alma
Armud
Banan
Nar


In [24]:
# İndeks və dəyərlə birlikdə
print("\nMeyvələr və indekslər:")
for indeks, meyvə in enumerate(meyvələr):
    print(f"{indeks}: {meyvə}")


Meyvələr və indekslər:
0: alma
1: armud
2: banan
3: nar


## While dövrü nümunələri

In [25]:
# say dəyişənini 0 olaraq təyin edir
say = 0

# Başlıq olaraq "While dövrü:" yazdırır
print("\nWhile dövrü:")

# say 5-dən kiçik olduğu müddətcə dövrü işləyir
while say < 5:
    # say dəyişəninin cari dəyərini boşluqla ayrılmış şəkildə çap edir
    print(say, end=' ')
    # say dəyişəninin dəyərini 1 artırır
    say += 1


While dövrü:
0 1 2 3 4 

In [26]:
# break və continue
print("\n\nBreak nümunəsi:")
say = 0
while True:
    print(say, end=' ')
    say += 1
    if say >= 5:
        break




Break nümunəsi:
0 1 2 3 4 

In [27]:
#continue amriyle biz bir nov bundan kec ve davam et deyirik
print("\n\nContinue nümunəsi:")
say = 0
while say < 10:
    say += 1
    if say % 2 == 0:
        continue
    print(say, end=' ')



Continue nümunəsi:
1 3 5 7 9 

## 2.1 Listlər

In [29]:
boş_list = []
rəqəmlər = [1, 2, 3, 4, 5]
qarışıq = [1, "iki", 3.0, True]
list_from_range = list(range(10))
list_from_string = list("Python")

print("Rəqəmlər:", rəqəmlər)
print("Qarışıq list:", qarışıq)
print("Range-dən list:", list_from_range)
print("String-dən list:", list_from_string)

Rəqəmlər: [1, 2, 3, 4, 5]
Qarışıq list: [1, 'iki', 3.0, True]
Range-dən list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
String-dən list: ['P', 'y', 't', 'h', 'o', 'n']


In [30]:
my_list = [1, 2, 3, 4, 5]

In [31]:
print("İlk element:", my_list[0])       # 1
print("Son element:", my_list[-1])      # 5
print("Slice 1-3:", my_list[1:3])      # [2, 3]
print("Slice başdan:", my_list[:3])     # [1, 2, 3]
print("Slice sona:", my_list[3:])       # [4, 5]
print("Addımlı slice:", my_list[::2])   # [1, 3, 5]


İlk element: 1
Son element: 5
Slice 1-3: [2, 3]
Slice başdan: [1, 2, 3]
Slice sona: [4, 5]
Addımlı slice: [1, 3, 5]


In [32]:
meyvələr = ["alma", "banan"]


In [33]:
meyvələr.append("nar")         # Sonuna əlavə
meyvələr.insert(1, "armud")    # Müəyyən yerə
print("Əlavədən sonra:", meyvələr)


Əlavədən sonra: ['alma', 'armud', 'banan', 'nar']


In [34]:
# Silmə
çıxarılan = meyvələr.pop(1)    # İndekslə sil
print(f"Çıxarılan: {çıxarılan}, Qalan: {meyvələr}")
meyvələr.remove("banan")       # Dəyərlə sil
print("Silmədən sonra:", meyvələr)


Çıxarılan: armud, Qalan: ['alma', 'banan', 'nar']
Silmədən sonra: ['alma', 'nar']


In [35]:
# Digər əməliyyatlar
rəqəmlər = [3, 1, 4, 2]
rəqəmlər.sort()                # Çeşidləmə
print("Çeşidlənmiş:", rəqəmlər)
rəqəmlər.reverse()             # Tərsinə çevirmə
print("Tərs:", rəqəmlər)


Çeşidlənmiş: [1, 2, 3, 4]
Tərs: [4, 3, 2, 1]


## List anlayışları (List Comprehensions)

In [38]:
kvadratlar = []
for x in range(10):
    kvadratlar.append(x**2)
print(kvadratlar)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [37]:
kvadratlar = [x**2 for x in range(10)]
print("Kvadratlar:", kvadratlar)

Kvadratlar: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [39]:
cüt_ədədlər = [x for x in range(20) if x % 2 == 0]
print("Cüt ədədlər:", cüt_ədədlər)


Cüt ədədlər: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [40]:
nəticələr = ["çox yaxşı" if x > 85 else "yaxşı" if x > 70 else "kafi" for x in [90, 75, 60]]
print("Nəticələr:", nəticələr)


Nəticələr: ['çox yaxşı', 'yaxşı', 'kafi']


In [41]:
boş_lüğət = {}
şagird = {
    "ad": "Əli",
    "yaş": 20,
    "ixtisas": "İnformatika",
    "fənnlər": ["Proqramlaşdırma", "Verilənlər Bazası"]
}

print("Tam lüğət:", şagird)
print("Ad:", şagird["ad"])
print("İlk fənn:", şagird["fənnlər"][0])

Tam lüğət: {'ad': 'Əli', 'yaş': 20, 'ixtisas': 'İnformatika', 'fənnlər': ['Proqramlaşdırma', 'Verilənlər Bazası']}
Ad: Əli
İlk fənn: Proqramlaşdırma


In [42]:
print("Açarlar:", şagird.keys())
print("Dəyərlər:", şagird.values())
print("Cütlər:", şagird.items())


Açarlar: dict_keys(['ad', 'yaş', 'ixtisas', 'fənnlər'])
Dəyərlər: dict_values(['Əli', 20, 'İnformatika', ['Proqramlaşdırma', 'Verilənlər Bazası']])
Cütlər: dict_items([('ad', 'Əli'), ('yaş', 20), ('ixtisas', 'İnformatika'), ('fənnlər', ['Proqramlaşdırma', 'Verilənlər Bazası'])])


In [43]:
şagird["universitet"] = "BDU"
print("\nƏlavədən sonra:", şagird)


Əlavədən sonra: {'ad': 'Əli', 'yaş': 20, 'ixtisas': 'İnformatika', 'fənnlər': ['Proqramlaşdırma', 'Verilənlər Bazası'], 'universitet': 'BDU'}


In [44]:
silinən = şagird.pop("yaş")
print(f"Silinən: {silinən}, Qalan: {şagird}")

Silinən: 20, Qalan: {'ad': 'Əli', 'ixtisas': 'İnformatika', 'fənnlər': ['Proqramlaşdırma', 'Verilənlər Bazası'], 'universitet': 'BDU'}


In [45]:
# Ədədlər siyahısı yaradır
ədədlər = [1, 2, 3, 4, 5]

# Siyahıdakı hər ədədin kvadratını açar-dəyər cütlüyü kimi saxlayan lüğət (dictionary) yaradır
kvadrat_lüğəti = {x: x**2 for x in ədədlər}

# Nəticədə yaranan kvadrat lüğətini çap edir
print("Kvadrat lüğəti:", kvadrat_lüğəti)

Kvadrat lüğəti: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [46]:
# kvadrat_lüğəti lüğətində olan cüt kvadrat dəyərləri seçib yeni lüğət yaradır
# yəni, kvadratın 2-yə bölünəndən 0 qalığı varsa, onu saxlayır
cüt_lüğət = {k: v for k, v in kvadrat_lüğəti.items() if v % 2 == 0}

# Nəticədə yaranan cüt kvadratlar lüğətini çap edir
print("Cüt kvadratlar:", cüt_lüğət)


Cüt kvadratlar: {2: 4, 4: 16}


In [47]:
çoxluq = {1, 2, 3, 3, 4, 4}
print("Çoxluq:", çoxluq)  # {1, 2, 3, 4}


Çoxluq: {1, 2, 3, 4}


In [48]:
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}

print("Birləşmə:", A.union(B))            # {1, 2, 3, 4, 5, 6}
print("Kəsişmə:", A.intersection(B))      # {3, 4}
print("Fərq (A-B):", A.difference(B))     # {1, 2}
print("Simmetrik fərq:", A.symmetric_difference(B))  # {1, 2, 5, 6}


Birləşmə: {1, 2, 3, 4, 5, 6}
Kəsişmə: {3, 4}
Fərq (A-B): {1, 2}
Simmetrik fərq: {1, 2, 5, 6}


In [49]:
koordinat = (40.4093, 49.8671)  # Bakı koordinatları
print("Tuple:", koordinat)
print("Enlik:", koordinat[0])
print("Uzunluq:", koordinat[1])

Tuple: (40.4093, 49.8671)
Enlik: 40.4093
Uzunluq: 49.8671


In [50]:
enlik, uzunluq = koordinat
print(f"Enlik: {enlik}, Uzunluq: {uzunluq}")


Enlik: 40.4093, Uzunluq: 49.8671


In [51]:
def kvadrat(x):
    """Verilən ədədin kvadratını qaytarır"""
    return x ** 2

print("5-in kvadratı:", kvadrat(5))

5-in kvadratı: 25


In [52]:
def ünvan_yarat(ad, şəhər="Bakı", ölkə="Azərbaycan"):
    """Ünvan yaradır"""
    return f"{ad}, {şəhər}, {ölkə}"


In [53]:
print(ünvan_yarat("Əli"))
print(ünvan_yarat("Aygün", "Gəncə"))
print(ünvan_yarat("John", "London", "İngiltərə"))


Əli, Bakı, Azərbaycan
Aygün, Gəncə, Azərbaycan
John, London, İngiltərə


In [54]:
def cəmi_hesabla(*rəqəmlər):
    """Verilən bütün rəqəmlərin cəmini hesablayır"""
    return sum(rəqəmlər)

In [55]:
print("Cəmi (1,2,3):", cəmi_hesabla(1, 2, 3))
print("Cəmi (4,5,6,7):", cəmi_hesabla(4, 5, 6, 7))

Cəmi (1,2,3): 6
Cəmi (4,5,6,7): 22


In [56]:
def şagird_məlumatı(**məlumat):
    """Şagird haqqında məlumat çap edir"""
    for açar, dəyər in məlumat.items():
        print(f"{açar}: {dəyər}")

şagird_məlumatı(ad="Əli", yaş=20, ixtisas="İnformatika")

ad: Əli
yaş: 20
ixtisas: İnformatika


In [57]:
# Lambda funksiyası ilə verilən ədədin kvadratını hesablayan funksiya yaradır
kvadrat = lambda x: x ** 2

# Lambda funksiyasını çağırıb 4-ün kvadratını çap edir
print("Lambda kvadrat:", kvadrat(4))

# Şagirdlərin ad və ballarını saxlayan siyahı (dictionary-lərdən ibarət)
şagirdlər = [
    {"ad": "Əli", "bal": 85},
    {"ad": "Aygün", "bal": 92},
    {"ad": "Vaqif", "bal": 78}
]

Lambda kvadrat: 16


In [58]:
sıralanmış = sorted(şagirdlər, key=lambda x: x["bal"], reverse=True)
print("Balına görə sıralanmış şagirdlər:")
for şagird in sıralanmış:
    print(şagird)


Balına görə sıralanmış şagirdlər:
{'ad': 'Aygün', 'bal': 92}
{'ad': 'Əli', 'bal': 85}
{'ad': 'Vaqif', 'bal': 78}


In [59]:
# 'nümunə.txt' adlı faylı yazmaq üçün açır (mövcud deyilsə yaradılır), UTF-8 kodlaşdırması ilə
with open('nümunə.txt', 'w', encoding='utf-8') as f:
    # Fayla üç sətir yazır, hər sətrin sonunda yeni sətir simvolu (\n) əlavə olunur
    f.write("Bu birinci sətirdir.\n")
    f.write("Bu ikinci sətirdir.\n")
    f.write("Bu üçüncü sətirdir.\n")

# Fayldan oxumaq üçün açır və məzmunu çap edir
print("\nFaylın tam məzmunu:")
with open('nümunə.txt', 'r', encoding='utf-8') as f:
    print(f.read())


Faylın tam məzmunu:
Bu birinci sətirdir.
Bu ikinci sətirdir.
Bu üçüncü sətirdir.



In [60]:
# Ekrana "Fayl sətir-sətir:" başlığını yazdırır
print("\nFayl sətir-sətir:")

# 'nümunə.txt' faylını oxumaq üçün açır, UTF-8 kodlaşdırması ilə
with open('nümunə.txt', 'r', encoding='utf-8') as f:
    # Fayldakı hər sətri bir-bir oxuyur
    for sətir in f:
        # Hər sətrin əvvəlində və sonunda olan boşluqları və yeni sətir simvolunu silərək çap edir
        print(sətir.strip())


Fayl sətir-sətir:
Bu birinci sətirdir.
Bu ikinci sətirdir.
Bu üçüncü sətirdir.


In [61]:
# csv modulunu import edir (CSV faylları ilə işləmək üçün)
import csv

# 'şagirdlər.csv' faylını yazmaq üçün açır, newline='' - əlavə boş sətirlərin qarşısını almaq üçün
with open('şagirdlər.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)  # CSV yazıcısını yaradır
    writer.writerow(["Ad", "Yaş", "İxtisas"])  # Başlıq sətrini yazır
    writer.writerow(["Əli", 20, "İnformatika"])  # Birinci şagird məlumatları
    writer.writerow(["Aygün", 21, "Riyaziyyat"])  # İkinci şagird məlumatları

# CSV faylını oxumaq və məzmunu çap etmək
print("\nCSV fayl məzmunu:")
with open('şagirdlər.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)  # CSV oxuyucusunu yaradır
    for sətir in reader:
        print(sətir)  # Hər sətri siyahı şəklində çap edir


CSV fayl məzmunu:
['Ad', 'Yaş', 'İxtisas']
['Əli', '20', 'İnformatika']
['Aygün', '21', 'Riyaziyyat']


In [62]:
try:
    # İstifadəçidən yaşını rəqəm olaraq daxil etməsini istəyir
    yaş = int(input("Yaşınızı daxil edin: "))
    # Daxil edilmiş yaşı çap edir
    print(f"Sizin yaşınız {yaş}-dir")

except ValueError:
    # Əgər daxil edilən dəyər tam ədəd deyilirsə, bu blok işə düşür
    print("Xəta: Yaş rəqəm olmalıdır!")

except Exception as e:
    # Digər bütün gözlənilməz xətaları tutub mesaj çap edir
    print(f"Gözlənilməz xəta: {e}")

finally:
    # Hər halda işləyəcək, icranın tamamlandığını bildirir
    print("İcra tamamlandı")

Yaşınızı daxil edin:  


Xəta: Yaş rəqəm olmalıdır!
İcra tamamlandı


In [63]:
class BalXətası(Exception):
    """Bal üçün xüsusi xəta sinfi"""
    pass

def bal_yoxla(bal):
    if bal < 0 or bal > 100:
        raise BalXətası("Bal 0-100 aralığında olmalıdır")
    return bal

In [64]:
try:
    print(bal_yoxla(85))  # Normal
    print(bal_yoxla(120)) # Xəta
except BalXətası as e:
    print(f"Xəta: {e}")

85
Xəta: Bal 0-100 aralığında olmalıdır


## Generator-lar (Generators)

In [65]:
def say_üstlü(n):
    """Sayğac generatoru"""
    for i in range(n):
        yield i ** 2  # yield generator yaradır

In [66]:
generator = say_üstlü(5)
print("Generator tipi:", type(generator))

Generator tipi: <class 'generator'>


In [67]:
print("Generator dəyərləri:")
for dəyər in generator:
    print(dəyər)

Generator dəyərləri:
0
1
4
9
16


In [69]:
import sys

In [70]:
list_rəqəmlər = [x for x in range(100000)]
print("List yaddaş ölçüsü:", sys.getsizeof(list_rəqəmlər), "bayt")

# Generator yaratmaq
generator_rəqəmlər = (x for x in range(100000))
print("Generator yaddaş ölçüsü:", sys.getsizeof(generator_rəqəmlər), "bayt")

List yaddaş ölçüsü: 800984 bayt
Generator yaddaş ölçüsü: 192 bayt


In [71]:
def sayğac():
    """Dayandırıla bilən sayğac generatoru"""
    say = 0
    while True:
        yield say
        say += 1

In [72]:
counter = sayğac()

# Bir neçə dəyər almaq
print("\nSayğac dəyərləri:")
print(next(counter))  # 0
print(next(counter))  # 1
print(next(counter))  # 2



Sayğac dəyərləri:
0
1
2


In [74]:
def orta_hesablayıcı():
    """Dəyər qəbul edən generator"""
    cəm = 0
    say = 0
    while True:
        dəyər = yield  # yield dəyər qəbul edir
        if dəyər is None:
            break
        cəm += dəyər
        say += 1
    yield cəm / say if say > 0 else 0

# İstifadə
ortalama = orta_hesablayıcı()
next(ortalama)  # Generatoru başlatmaq

ortalama.send(10)  # Dəyər göndərmək
ortalama.send(20)
ortalama.send(30)

try:
    ortalama.send(None)  # Dayandırmaq üçün
except StopIteration as e:
    print("\nOrta dəyər:", e.value)  # 20.0

## Decorator-lar

In [75]:
# Funksiyanın icra vaxtını ölçən decorator funksiyası
def vaxt_ölçən(func):
    """Funksiyanın icra vaxtını ölçən decorator"""

    # Əhatə edən (wrapper) funksiya, orijinal funksiyanın arqumentlərini qəbul edir
    def əhatə_edici(*args, **kwargs):
        import time  # vaxt ölçmək üçün time modulunu import edir
        başlama = time.time()  # İcra başlamazdan əvvəl vaxtı götürür
        nəticə = func(*args, **kwargs)  # Orijinal funksiyanı çağırır və nəticəsini alır
        bitmə = time.time()  # İcra bitdikdən sonra vaxtı götürür
        # Funksiyanın adı və icra müddətini saniyə ilə çap edir
        print(f"{func.__name__} funksiyası {bitmə - başlama:.4f} saniyə çəkdi")
        return nəticə  # Orijinal funksiyanın nəticəsini qaytarır

    return əhatə_edici  # Decorator əhatə edən funksiyanı qaytarır


In [76]:
# vaxt_ölçən decorator-u ilə işarələnmiş funksiya
@vaxt_ölçən
def uzun_hesablama(n):
    """Uzun hesablama simulyasiyası"""
    toplam = 0
    # 0-dan n-1-ə qədər olan ədədləri toplamaq üçün dövr
    for i in range(n):
        toplam += i
    # Toplamı qaytarır
    return toplam

# Uzun hesablama funksiyasını çağırır və nəticəsini çap edir
print("\nUzun hesablama nəticəsi:", uzun_hesablama(1000000))


uzun_hesablama funksiyası 0.1506 saniyə çəkdi

Uzun hesablama nəticəsi: 499999500000


### 2.2 Parametrli decoratorlar

In [77]:
# Funksiyanı müəyyən sayda təkrar edən decorator yaradır
def təkrar_et(sayı):
    """Funksiyanı müəyyən sayda təkrar edən decorator"""

    # Əsl decorator funksiyası, orijinal funksiyanı qəbul edir
    def real_decorator(func):

        # Əhatə edən funksiya, orijinal funksiyanın arqumentlərini qəbul edir
        def əhatə_edici(*args, **kwargs):
            for _ in range(sayı):
                # Funksiyanı təkrar-təkrar çağırır
                nəticə = func(*args, **kwargs)
            # Sonuncu çağırışın nəticəsini qaytarır
            return nəticə

        return əhatə_edici

    return real_decorator


In [78]:
# 'təkrar_et' decorator-u 3 dəfə işləyəcək şəkildə tətbiq edilir
@təkrar_et(sayı=3)
def salam_ver(ad):
    """Salam verən funksiya"""
    # Verilən ada salam verir
    print(f"Salam, {ad}!")

print("\nTəkrar decorator nümunəsi:")

# salam_ver funksiyasını çağırır, nəticədə 3 dəfə "Salam, Əli!" çap olunur
salam_ver("Əli")


Təkrar decorator nümunəsi:
Salam, Əli!
Salam, Əli!
Salam, Əli!


In [2]:
from hesablamalar import cemi, orta, PI

reqemler = [1, 2, 3, 4, 5]
print("Cəmi:", cemi(reqemler))
print("Orta:", orta(reqemler))
print("PI dəyəri:", PI)

Cəmi: 15
Orta: 3.0
PI dəyəri: 3.14159


In [3]:
import sys
print("\nModul axtarış yolları:")
for yol in sys.path:
    print(yol)


Modul axtarış yolları:
C:\Users\goyle\AppData\Local\Programs\Python\Python313\python313.zip
C:\Users\goyle\AppData\Local\Programs\Python\Python313\DLLs
C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib
C:\Users\goyle\AppData\Local\Programs\Python\Python313

C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib\site-packages
C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib\site-packages\win32
C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib\site-packages\win32\lib
C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib\site-packages\Pythonwin


In [4]:
if __name__ == "__main__":
    print("\nBu modul birbaşa işə salınıb")
else:
    print("\nBu modul import edilib")


Bu modul birbaşa işə salınıb


In [5]:
import os
print("Cari qovluq:", os.getcwd())

Cari qovluq: C:\Users\goyle\OneDrive\Desktop\AIlab_python


In [6]:
print("\nQovluq məzmunu:")
for element in os.listdir():
    print(element)


Qovluq məzmunu:
.ipynb_checkpoints
hesablamalar.py
nümunə.txt
python.ipynb
__pycache__
şagirdlər.csv


In [7]:
if os.path.exists("hesablamalar.py"):
    print("\nFayl məlumatı:")
    print("Ölçü:", os.path.getsize("hesablamalar.py"), "bayt")
    print("Son dəyişmə:", os.path.getmtime("hesablamalar.py"))



Fayl məlumatı:
Ölçü: 128 bayt
Son dəyişmə: 1751302382.6738274


In [1]:
import math

print("\nRiyazi funksiyalar:")
print("Kvadrat kök:", math.sqrt(16))
print("Sinus:", math.sin(math.pi/2))
print("e üstü:", math.exp(1))
print("Faktorial:", math.factorial(5))
print("GCD (ƏBOB):", math.gcd(48, 18))



Riyazi funksiyalar:
Kvadrat kök: 4.0
Sinus: 1.0
e üstü: 2.718281828459045
Faktorial: 120
GCD (ƏBOB): 6


In [2]:
from datetime import datetime, timedelta

# Hazırkı tarix və vaxt
indiki = datetime.now()
print("\nHazırkı vaxt:", indiki)

# Formatlama
print("Formatlanmış:", indiki.strftime("%d.%m.%Y %H:%M"))

# Tarix əməliyyatları
bir_həftə_sonra = indiki + timedelta(days=7)
print("Bir həftə sonra:", bir_həftə_sonra)


Hazırkı vaxt: 2025-07-01 12:09:28.272560
Formatlanmış: 01.07.2025 12:09
Bir həftə sonra: 2025-07-08 12:09:28.272560


In [3]:
import random

print("\nTəsadüfi ədədlər:")
print("0-1 arası:", random.random())
print("1-10 arası tam:", random.randint(1, 10))
print("Təsadüfi seçim:", random.choice(["alma", "armud", "banan"]))

# Listi qarışdırmaq
list = [1, 2, 3, 4, 5]
random.shuffle(list)
print("Qarışdırılmış list:", list)


Təsadüfi ədədlər:
0-1 arası: 0.9060982721086299
1-10 arası tam: 8
Təsadüfi seçim: banan
Qarışdırılmış list: [5, 3, 2, 1, 4]


In [4]:
import re
mətndəki_rəqəmlər = re.findall(r'\d+', 'Salam 123, Nə var 456?')
print("\nMətndəki rəqəmlər:", mətndəki_rəqəmlər)




Mətndəki rəqəmlər: ['123', '456']
