# NumPy və Pandas Kitabxanalarına Giriş

In [46]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

# 1D array yaratmaq
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)
print("Ölçü:", arr1d.shape)

1D Array:
[1 2 3 4 5]
Ölçü: (5,)


In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2d)
print("Ölçü:", arr2d.shape)


2D Array:
[[1 2 3]
 [4 5 6]]
Ölçü: (2, 3)


In [3]:
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 4))
range_arr = np.arange(0, 10, 2)  # 0-dan 10-a qədər 2 addımla
random_arr = np.random.rand(3, 3)  # 0-1 arası random ədədlər

print("\nXüsusi Arraylər:")
print("Zeros:\n", zeros_arr)
print("Ones:\n", ones_arr)
print("Arange:", range_arr)
print("Random:\n", random_arr)


Xüsusi Arraylər:
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Arange: [0 2 4 6 8]
Random:
 [[0.39063779 0.36104106 0.1015619 ]
 [0.33025401 0.89911428 0.72084756]
 [0.91774524 0.29058706 0.59117338]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Əsas riyazi əməliyyatlar
print("Toplama:", a + b)
print("Vurma:", a * b)  # Element-wise vurma
print("Nöqtə hasil:", np.dot(a, b))  # Dot product

# Universal funksiyalar (ufuncs)
print("Sinus:", np.sin(a))
print("Eksponent:", np.exp(a))
print("Kvadrat kök:", np.sqrt(a))

Toplama: [5 7 9]
Vurma: [ 4 10 18]
Nöqtə hasil: 32
Sinus: [0.84147098 0.90929743 0.14112001]
Eksponent: [ 2.71828183  7.3890561  20.08553692]
Kvadrat kök: [1.         1.41421356 1.73205081]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Orijinal Array:\n", arr)
print("İlk sətir:", arr[0])
print("Son sütun:", arr[:, -1])
print("Orta element:", arr[1, 1])
print("Sub-array:\n", arr[:2, 1:])

# Boolean indexing
print("\nBoolean Indexing:")
print(arr[arr > 5])

Orijinal Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
İlk sətir: [1 2 3]
Son sütun: [3 6 9]
Orta element: 5
Sub-array:
 [[2 3]
 [5 6]]

Boolean Indexing:
[6 7 8 9]


In [6]:
arr = np.arange(1, 10)
print("Orijinal:", arr)

# Yenidən şəkilləndirmə
reshaped = arr.reshape(3, 3)
print("\nYenidən şəkilləndirilmiş:\n", reshaped)

# Düzəltmə
flattened = reshaped.flatten()
print("Düzəldilmiş:", flattened)

# Transpoz
transposed = reshaped.T
print("Transpoz:\n", transposed)

Orijinal: [1 2 3 4 5 6 7 8 9]

Yenidən şəkilləndirilmiş:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Düzəldilmiş: [1 2 3 4 5 6 7 8 9]
Transpoz:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
data = np.random.randint(1, 100, size=(5, 5))

print("Data:\n", data)
print("\nStatistikalar:")
print("Orta:", np.mean(data))
print("Median:", np.median(data))
print("Standart sapma:", np.std(data))
print("Minimum:", np.min(data))
print("Maksimum:", np.max(data))
print("Sütun cəmi:", np.sum(data, axis=0))
print("Sətir ortası:", np.mean(data, axis=1))

Data:
 [[15 68 67 39 39]
 [17 60 56 86 98]
 [68 82  7 94 48]
 [ 7 29 48 58 25]
 [42 45 97 95 21]]

Statistikalar:
Orta: 52.44
Median: 48.0
Standart sapma: 28.312654414589954
Minimum: 7
Maksimum: 98
Sütun cəmi: [149 284 275 372 231]
Sətir ortası: [45.6 63.4 59.8 33.4 60. ]


## 2. Pandas Kitabxanası

In [8]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [9]:
import pandas as pd

# Dictionary-dən DataFrame yaratmaq
data = {
    'Ad': ['Əli', 'Aygün', 'Vaqif', 'Günay'],
    'Yaş': [25, 30, 35, 28],
    'Şəhər': ['Bakı', 'Gəncə', 'Sumqayıt', 'Bakı']
}

df = pd.DataFrame(data)
print("DataFrame:")
print(df)

DataFrame:
      Ad  Yaş     Şəhər
0    Əli   25      Bakı
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Bakı


In [10]:
print("\nƏsas Əməliyyatlar:")
print("İlk 2 sətir:\n", df.head(2))
print("\nTəsviri statistika:\n", df.describe())
print("\nSütunlar:", df.columns)
print("\nYaş sütunu:\n", df['Yaş'])
print("\nYaş > 26 olanlar:\n", df[df['Yaş'] > 26])


Əsas Əməliyyatlar:
İlk 2 sətir:
       Ad  Yaş  Şəhər
0    Əli   25   Bakı
1  Aygün   30  Gəncə

Təsviri statistika:
              Yaş
count   4.000000
mean   29.500000
std     4.203173
min    25.000000
25%    27.250000
50%    29.000000
75%    31.250000
max    35.000000

Sütunlar: Index(['Ad', 'Yaş', 'Şəhər'], dtype='object')

Yaş sütunu:
 0    25
1    30
2    35
3    28
Name: Yaş, dtype: int64

Yaş > 26 olanlar:
       Ad  Yaş     Şəhər
1  Aygün   30     Gəncə
2  Vaqif   35  Sumqayıt
3  Günay   28      Bakı


In [11]:
print("\nQruplama Əməliyyatları:")
print("Şəhərə görə orta yaş:\n", df.groupby('Şəhər')['Yaş'].mean())
# print("\nTəhsilə görə say:\n", df['Təhsil'].value_counts())

# Pivot cədvəl
print("\nPivot Cədvəl:")
print(pd.pivot_table(df, values='Yaş', index='Şəhər', aggfunc='mean'))


Qruplama Əməliyyatları:
Şəhərə görə orta yaş:
 Şəhər
Bakı        26.5
Gəncə       30.0
Sumqayıt    35.0
Name: Yaş, dtype: float64

Pivot Cədvəl:
           Yaş
Şəhər         
Bakı      26.5
Gəncə     30.0
Sumqayıt  35.0


In [59]:
df.loc[1, 'Yaş'] = None
df.loc[3, 'Şəhər'] = None

print("\nÇatışmayan məlumatlarla DataFrame:")
print(df)


Çatışmayan məlumatlarla DataFrame:
      Ad   Yaş     Şəhər
0    Əli  25.0      Bakı
1  Aygün   NaN     Gəncə
2  Vaqif  35.0  Sumqayıt
3  Günay  28.0      None


In [60]:
print("\nÇatışmayan məlumatların sayı:")
print(df.isnull().sum())


Çatışmayan məlumatların sayı:
Ad       0
Yaş      1
Şəhər    1
dtype: int64


In [61]:
filled_df = df.fillna({'Yaş': df['Yaş'].mean(), 'Şəhər': 'Naməlum'})
print("\nDoldurulmuş DataFrame:")
print(filled_df)


Doldurulmuş DataFrame:
      Ad        Yaş     Şəhər
0    Əli  25.000000      Bakı
1  Aygün  29.333333     Gəncə
2  Vaqif  35.000000  Sumqayıt
3  Günay  28.000000   Naməlum


In [62]:
df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})


In [63]:
concat_df = pd.concat([df1, df2], ignore_index=True)
print("\nBirləşdirilmiş DataFrame:")
print(concat_df)


Birləşdirilmiş DataFrame:
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [64]:
left = pd.DataFrame({'key': ['K0', 'K1'], 'A': ['A0', 'A1']})
right = pd.DataFrame({'key': ['K0', 'K1'], 'B': ['B0', 'B1']})

merged_df = pd.merge(left, right, on='key')
print("\nMerge edilmiş DataFrame:")
print(merged_df)


Merge edilmiş DataFrame:
  key   A   B
0  K0  A0  B0
1  K1  A1  B1


# Python Basics


### 1.1 Dəyişənlər və Operatorlar

## Əsas dəyişən tipləri

In [4]:
tam_ədəd = 42                  # int
kəsr_ədəd = 3.14               # float
mətn = "Salam, Dünya!"         # str
məntiqi = True                 # bool
heç_nə = None                  # NoneType

### Çoxsətirli mətn

In [5]:
çoxsətirli = """
Bu çoxsətirli
mətn nümunəsidir.
"""

In [7]:
print(çoxsətirli)


Bu çoxsətirli
mətn nümunəsidir.



In [8]:
çoxsətirli

'\nBu çoxsətirli\nmətn nümunəsidir.\n'

## Dinamik tip dəyişmə

In [10]:
dəyişən = 10
print(type(dəyişən))  # <class 'int'>
dəyişən = "on"
print(type(dəyişən))  # <class 'str'>


<class 'int'>
<class 'str'>


## Operatorlar nümunələri

In [11]:
a, b = 10, 3

print("Toplama:", a + b)       # 13
print("Çıxma:", a - b)         # 7
print("Vurma:", a * b)         # 30
print("Bölmə:", a / b)         # 3.333...
print("Tam bölmə:", a // b)    # 3
print("Qalıq:", a % b)         # 1
print("Üst:", a ** b)          # 1000


Toplama: 13
Çıxma: 7
Vurma: 30
Bölmə: 3.3333333333333335
Tam bölmə: 3
Qalıq: 1
Üst: 1000


## Müqayisə operatorları

In [12]:
print("a > b:", a > b)         # True
print("a == b:", a == b)       # False
print("a != b:", a != b)       # True

a > b: True
a == b: False
a != b: True


## Məntiqi operatorlar

In [13]:
print("AND:", True and False)  # False
print("OR:", True or False)    # True
print("NOT:", not True)        # False


AND: False
OR: True
NOT: False


# 1.2 Şərt İfadələri

In [15]:
bal = 85

if bal >= 90:
    print("Əla!")
elif bal >= 70:
    print("Yaxşı!")
elif bal >= 50:
    print("Qənaətbəxş")
else:
    print("Kəsildiniz")

Yaxşı!


### İç-içə şərtlər

In [17]:
yaş = 20
təhsil = "ali"

if yaş >= 18:
    if təhsil == "ali":
        print("İş üçün uyğunsunuz")
    else:
        print("Təhsil şərtinə uyğun deyilsiniz")
else:
    print("Yaş şərtinə uyğun deyilsiniz")

İş üçün uyğunsunuz


In [18]:
x = 10
y = 20
kiçik = x if x < y else y
print("Kiçik olan:", kiçik)

Kiçik olan: 10


# 1.3 Dövrlər

In [20]:
print("0-dan 4-ə qədər:")
for i in range(5):
    print(i, end=' ')

0-dan 4-ə qədər:
0 1 2 3 4 

In [21]:
print("\n\n5-dən 9-a qədər:")
for i in range(5, 10):
    print(i, end=' ')




5-dən 9-a qədər:
5 6 7 8 9 

In [22]:
print("\n\n0-dan 10-a qədər 2 addım:")
for i in range(0, 11, 2):
    print(i, end=' ')



0-dan 10-a qədər 2 addım:
0 2 4 6 8 10 

In [23]:
meyvələr = ["alma", "armud", "banan", "nar"]
print("\n\nMeyvələr siyahısı:")
for meyvə in meyvələr:
    print(meyvə.title())



Meyvələr siyahısı:
Alma
Armud
Banan
Nar


In [24]:
# İndeks və dəyərlə birlikdə
print("\nMeyvələr və indekslər:")
for indeks, meyvə in enumerate(meyvələr):
    print(f"{indeks}: {meyvə}")


Meyvələr və indekslər:
0: alma
1: armud
2: banan
3: nar


## While dövrü nümunələri

In [25]:
say = 0
print("\nWhile dövrü:")
while say < 5:
    print(say, end=' ')
    say += 1


While dövrü:
0 1 2 3 4 

In [26]:
# break və continue
print("\n\nBreak nümunəsi:")
say = 0
while True:
    print(say, end=' ')
    say += 1
    if say >= 5:
        break




Break nümunəsi:
0 1 2 3 4 

In [27]:
print("\n\nContinue nümunəsi:")
say = 0
while say < 10:
    say += 1
    if say % 2 == 0:
        continue
    print(say, end=' ')



Continue nümunəsi:
1 3 5 7 9 

## 2.1 Listlər

In [29]:
boş_list = []
rəqəmlər = [1, 2, 3, 4, 5]
qarışıq = [1, "iki", 3.0, True]
list_from_range = list(range(10))
list_from_string = list("Python")

print("Rəqəmlər:", rəqəmlər)
print("Qarışıq list:", qarışıq)
print("Range-dən list:", list_from_range)
print("String-dən list:", list_from_string)

Rəqəmlər: [1, 2, 3, 4, 5]
Qarışıq list: [1, 'iki', 3.0, True]
Range-dən list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
String-dən list: ['P', 'y', 't', 'h', 'o', 'n']


In [30]:
my_list = [1, 2, 3, 4, 5]

In [31]:
print("İlk element:", my_list[0])       # 1
print("Son element:", my_list[-1])      # 5
print("Slice 1-3:", my_list[1:3])      # [2, 3]
print("Slice başdan:", my_list[:3])     # [1, 2, 3]
print("Slice sona:", my_list[3:])       # [4, 5]
print("Addımlı slice:", my_list[::2])   # [1, 3, 5]


İlk element: 1
Son element: 5
Slice 1-3: [2, 3]
Slice başdan: [1, 2, 3]
Slice sona: [4, 5]
Addımlı slice: [1, 3, 5]


In [32]:
meyvələr = ["alma", "banan"]


In [33]:
meyvələr.append("nar")         # Sonuna əlavə
meyvələr.insert(1, "armud")    # Müəyyən yerə
print("Əlavədən sonra:", meyvələr)


Əlavədən sonra: ['alma', 'armud', 'banan', 'nar']


In [34]:
# Silmə
çıxarılan = meyvələr.pop(1)    # İndekslə sil
print(f"Çıxarılan: {çıxarılan}, Qalan: {meyvələr}")
meyvələr.remove("banan")       # Dəyərlə sil
print("Silmədən sonra:", meyvələr)


Çıxarılan: armud, Qalan: ['alma', 'banan', 'nar']
Silmədən sonra: ['alma', 'nar']


In [35]:
# Digər əməliyyatlar
rəqəmlər = [3, 1, 4, 2]
rəqəmlər.sort()                # Çeşidləmə
print("Çeşidlənmiş:", rəqəmlər)
rəqəmlər.reverse()             # Tərsinə çevirmə
print("Tərs:", rəqəmlər)


Çeşidlənmiş: [1, 2, 3, 4]
Tərs: [4, 3, 2, 1]


## List anlayışları (List Comprehensions)

In [38]:
kvadratlar = []
for x in range(10):
    kvadratlar.append(x**2)
print(kvadratlar)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [37]:
kvadratlar = [x**2 for x in range(10)]
print("Kvadratlar:", kvadratlar)

Kvadratlar: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [39]:
cüt_ədədlər = [x for x in range(20) if x % 2 == 0]
print("Cüt ədədlər:", cüt_ədədlər)


Cüt ədədlər: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [40]:
nəticələr = ["çox yaxşı" if x > 85 else "yaxşı" if x > 70 else "kafi" for x in [90, 75, 60]]
print("Nəticələr:", nəticələr)


Nəticələr: ['çox yaxşı', 'yaxşı', 'kafi']


In [41]:
boş_lüğət = {}
şagird = {
    "ad": "Əli",
    "yaş": 20,
    "ixtisas": "İnformatika",
    "fənnlər": ["Proqramlaşdırma", "Verilənlər Bazası"]
}

print("Tam lüğət:", şagird)
print("Ad:", şagird["ad"])
print("İlk fənn:", şagird["fənnlər"][0])

Tam lüğət: {'ad': 'Əli', 'yaş': 20, 'ixtisas': 'İnformatika', 'fənnlər': ['Proqramlaşdırma', 'Verilənlər Bazası']}
Ad: Əli
İlk fənn: Proqramlaşdırma


In [42]:
print("Açarlar:", şagird.keys())
print("Dəyərlər:", şagird.values())
print("Cütlər:", şagird.items())


Açarlar: dict_keys(['ad', 'yaş', 'ixtisas', 'fənnlər'])
Dəyərlər: dict_values(['Əli', 20, 'İnformatika', ['Proqramlaşdırma', 'Verilənlər Bazası']])
Cütlər: dict_items([('ad', 'Əli'), ('yaş', 20), ('ixtisas', 'İnformatika'), ('fənnlər', ['Proqramlaşdırma', 'Verilənlər Bazası'])])


In [43]:
şagird["universitet"] = "BDU"
print("\nƏlavədən sonra:", şagird)


Əlavədən sonra: {'ad': 'Əli', 'yaş': 20, 'ixtisas': 'İnformatika', 'fənnlər': ['Proqramlaşdırma', 'Verilənlər Bazası'], 'universitet': 'BDU'}


In [44]:
silinən = şagird.pop("yaş")
print(f"Silinən: {silinən}, Qalan: {şagird}")

Silinən: 20, Qalan: {'ad': 'Əli', 'ixtisas': 'İnformatika', 'fənnlər': ['Proqramlaşdırma', 'Verilənlər Bazası'], 'universitet': 'BDU'}


In [45]:
ədədlər = [1, 2, 3, 4, 5]
kvadrat_lüğəti = {x: x**2 for x in ədədlər}
print("Kvadrat lüğəti:", kvadrat_lüğəti)

Kvadrat lüğəti: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [46]:
cüt_lüğət = {k: v for k, v in kvadrat_lüğəti.items() if v % 2 == 0}
print("Cüt kvadratlar:", cüt_lüğət)

Cüt kvadratlar: {2: 4, 4: 16}


In [47]:
çoxluq = {1, 2, 3, 3, 4, 4}
print("Çoxluq:", çoxluq)  # {1, 2, 3, 4}


Çoxluq: {1, 2, 3, 4}


In [48]:
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}

print("Birləşmə:", A.union(B))            # {1, 2, 3, 4, 5, 6}
print("Kəsişmə:", A.intersection(B))      # {3, 4}
print("Fərq (A-B):", A.difference(B))     # {1, 2}
print("Simmetrik fərq:", A.symmetric_difference(B))  # {1, 2, 5, 6}


Birləşmə: {1, 2, 3, 4, 5, 6}
Kəsişmə: {3, 4}
Fərq (A-B): {1, 2}
Simmetrik fərq: {1, 2, 5, 6}


In [49]:
koordinat = (40.4093, 49.8671)  # Bakı koordinatları
print("Tuple:", koordinat)
print("Enlik:", koordinat[0])
print("Uzunluq:", koordinat[1])

Tuple: (40.4093, 49.8671)
Enlik: 40.4093
Uzunluq: 49.8671


In [50]:
enlik, uzunluq = koordinat
print(f"Enlik: {enlik}, Uzunluq: {uzunluq}")


Enlik: 40.4093, Uzunluq: 49.8671


In [51]:
def kvadrat(x):
    """Verilən ədədin kvadratını qaytarır"""
    return x ** 2

print("5-in kvadratı:", kvadrat(5))

5-in kvadratı: 25


In [52]:
def ünvan_yarat(ad, şəhər="Bakı", ölkə="Azərbaycan"):
    """Ünvan yaradır"""
    return f"{ad}, {şəhər}, {ölkə}"


In [53]:
print(ünvan_yarat("Əli"))
print(ünvan_yarat("Aygün", "Gəncə"))
print(ünvan_yarat("John", "London", "İngiltərə"))


Əli, Bakı, Azərbaycan
Aygün, Gəncə, Azərbaycan
John, London, İngiltərə


In [54]:
def cəmi_hesabla(*rəqəmlər):
    """Verilən bütün rəqəmlərin cəmini hesablayır"""
    return sum(rəqəmlər)

In [55]:
print("Cəmi (1,2,3):", cəmi_hesabla(1, 2, 3))
print("Cəmi (4,5,6,7):", cəmi_hesabla(4, 5, 6, 7))

Cəmi (1,2,3): 6
Cəmi (4,5,6,7): 22


In [56]:
def şagird_məlumatı(**məlumat):
    """Şagird haqqında məlumat çap edir"""
    for açar, dəyər in məlumat.items():
        print(f"{açar}: {dəyər}")

şagird_məlumatı(ad="Əli", yaş=20, ixtisas="İnformatika")

ad: Əli
yaş: 20
ixtisas: İnformatika


In [57]:
kvadrat = lambda x: x ** 2
print("Lambda kvadrat:", kvadrat(4))

# Sıralama üçün lambda
şagirdlər = [
    {"ad": "Əli", "bal": 85},
    {"ad": "Aygün", "bal": 92},
    {"ad": "Vaqif", "bal": 78}
]

Lambda kvadrat: 16


In [58]:
sıralanmış = sorted(şagirdlər, key=lambda x: x["bal"], reverse=True)
print("Balına görə sıralanmış şagirdlər:")
for şagird in sıralanmış:
    print(şagird)


Balına görə sıralanmış şagirdlər:
{'ad': 'Aygün', 'bal': 92}
{'ad': 'Əli', 'bal': 85}
{'ad': 'Vaqif', 'bal': 78}


In [59]:
with open('nümunə.txt', 'w', encoding='utf-8') as f:
    f.write("Bu birinci sətirdir.\n")
    f.write("Bu ikinci sətirdir.\n")
    f.write("Bu üçüncü sətirdir.\n")

# Fayldan oxumaq
print("\nFaylın tam məzmunu:")
with open('nümunə.txt', 'r', encoding='utf-8') as f:
    print(f.read())



Faylın tam məzmunu:
Bu birinci sətirdir.
Bu ikinci sətirdir.
Bu üçüncü sətirdir.



In [60]:
print("\nFayl sətir-sətir:")
with open('nümunə.txt', 'r', encoding='utf-8') as f:
    for sətir in f:
        print(sətir.strip())



Fayl sətir-sətir:
Bu birinci sətirdir.
Bu ikinci sətirdir.
Bu üçüncü sətirdir.


In [61]:
import csv


with open('şagirdlər.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(["Ad", "Yaş", "İxtisas"])
    writer.writerow(["Əli", 20, "İnformatika"])
    writer.writerow(["Aygün", 21, "Riyaziyyat"])

# CSV oxumaq
print("\nCSV fayl məzmunu:")
with open('şagirdlər.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    for sətir in reader:
        print(sətir)


CSV fayl məzmunu:
['Ad', 'Yaş', 'İxtisas']
['Əli', '20', 'İnformatika']
['Aygün', '21', 'Riyaziyyat']


In [62]:
try:
    yaş = int(input("Yaşınızı daxil edin: "))
    print(f"Sizin yaşınız {yaş}-dir")
except ValueError:
    print("Xəta: Yaş rəqəm olmalıdır!")
except Exception as e:
    print(f"Gözlənilməz xəta: {e}")
finally:
    print("İcra tamamlandı")

Yaşınızı daxil edin:  


Xəta: Yaş rəqəm olmalıdır!
İcra tamamlandı


In [63]:
class BalXətası(Exception):
    """Bal üçün xüsusi xəta sinfi"""
    pass

def bal_yoxla(bal):
    if bal < 0 or bal > 100:
        raise BalXətası("Bal 0-100 aralığında olmalıdır")
    return bal

In [64]:

try:
    print(bal_yoxla(85))  # Normal
    print(bal_yoxla(120)) # Xəta
except BalXətası as e:
    print(f"Xəta: {e}")


85
Xəta: Bal 0-100 aralığında olmalıdır


## Generator-lar (Generators)

In [65]:
def say_üstlü(n):
    """Sayğac generatoru"""
    for i in range(n):
        yield i ** 2  # yield generator yaradır

In [66]:
generator = say_üstlü(5)
print("Generator tipi:", type(generator))

Generator tipi: <class 'generator'>


In [67]:
print("Generator dəyərləri:")
for dəyər in generator:
    print(dəyər)
    

Generator dəyərləri:
0
1
4
9
16


In [69]:
import sys

In [70]:
list_rəqəmlər = [x for x in range(100000)]
print("List yaddaş ölçüsü:", sys.getsizeof(list_rəqəmlər), "bayt")

# Generator yaratmaq
generator_rəqəmlər = (x for x in range(100000))
print("Generator yaddaş ölçüsü:", sys.getsizeof(generator_rəqəmlər), "bayt")

List yaddaş ölçüsü: 800984 bayt
Generator yaddaş ölçüsü: 192 bayt


In [71]:
def sayğac():
    """Dayandırıla bilən sayğac generatoru"""
    say = 0
    while True:
        yield say
        say += 1

In [72]:
counter = sayğac()

# Bir neçə dəyər almaq
print("\nSayğac dəyərləri:")
print(next(counter))  # 0
print(next(counter))  # 1
print(next(counter))  # 2



Sayğac dəyərləri:
0
1
2


In [74]:
def orta_hesablayıcı():
    """Dəyər qəbul edən generator"""
    cəm = 0
    say = 0
    while True:
        dəyər = yield  # yield dəyər qəbul edir
        if dəyər is None:
            break
        cəm += dəyər
        say += 1
    yield cəm / say if say > 0 else 0

# İstifadə
ortalama = orta_hesablayıcı()
next(ortalama)  # Generatoru başlatmaq

ortalama.send(10)  # Dəyər göndərmək
ortalama.send(20)
ortalama.send(30)

try:
    ortalama.send(None)  # Dayandırmaq üçün
except StopIteration as e:
    print("\nOrta dəyər:", e.value)  # 20.0

## Decorator-lar

In [75]:
def vaxt_ölçən(func):
    """Funksiyanın icra vaxtını ölçən decorator"""
    def əhatə_edici(*args, **kwargs):
        import time
        başlama = time.time()
        nəticə = func(*args, **kwargs)
        bitmə = time.time()
        print(f"{func.__name__} funksiyası {bitmə - başlama:.4f} saniyə çəkdi")
        return nəticə
    return əhatə_edici

In [76]:
@vaxt_ölçən
def uzun_hesablama(n):
    """Uzun hesablama simulyasiyası"""
    toplam = 0
    for i in range(n):
        toplam += i
    return toplam

print("\nUzun hesablama nəticəsi:", uzun_hesablama(1000000))

uzun_hesablama funksiyası 0.1506 saniyə çəkdi

Uzun hesablama nəticəsi: 499999500000


### 2.2 Parametrli decoratorlar

In [77]:
def təkrar_et(sayı):
    """Funksiyanı müəyyən sayda təkrar edən decorator"""
    def real_decorator(func):
        def əhatə_edici(*args, **kwargs):
            for _ in range(sayı):
                nəticə = func(*args, **kwargs)
            return nəticə
        return əhatə_edici
    return real_decorator

In [78]:
@təkrar_et(sayı=3)
def salam_ver(ad):
    """Salam verən funksiya"""
    print(f"Salam, {ad}!")

print("\nTəkrar decorator nümunəsi:")
salam_ver("Əli")


Təkrar decorator nümunəsi:
Salam, Əli!
Salam, Əli!
Salam, Əli!


In [2]:
from hesablamalar import cemi, orta, PI

reqemler = [1, 2, 3, 4, 5]
print("Cəmi:", cemi(reqemler))
print("Orta:", orta(reqemler))
print("PI dəyəri:", PI)

Cəmi: 15
Orta: 3.0
PI dəyəri: 3.14159


In [3]:
import sys
print("\nModul axtarış yolları:")
for yol in sys.path:
    print(yol)


Modul axtarış yolları:
C:\Users\goyle\AppData\Local\Programs\Python\Python313\python313.zip
C:\Users\goyle\AppData\Local\Programs\Python\Python313\DLLs
C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib
C:\Users\goyle\AppData\Local\Programs\Python\Python313

C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib\site-packages
C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib\site-packages\win32
C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib\site-packages\win32\lib
C:\Users\goyle\AppData\Local\Programs\Python\Python313\Lib\site-packages\Pythonwin


In [4]:
if __name__ == "__main__":
    print("\nBu modul birbaşa işə salınıb")
else:
    print("\nBu modul import edilib")


Bu modul birbaşa işə salınıb


In [5]:
import os
print("Cari qovluq:", os.getcwd())

Cari qovluq: C:\Users\goyle\OneDrive\Desktop\AIlab_python


In [6]:
print("\nQovluq məzmunu:")
for element in os.listdir():
    print(element)


Qovluq məzmunu:
.ipynb_checkpoints
hesablamalar.py
nümunə.txt
python.ipynb
__pycache__
şagirdlər.csv


In [7]:
if os.path.exists("hesablamalar.py"):
    print("\nFayl məlumatı:")
    print("Ölçü:", os.path.getsize("hesablamalar.py"), "bayt")
    print("Son dəyişmə:", os.path.getmtime("hesablamalar.py"))



Fayl məlumatı:
Ölçü: 128 bayt
Son dəyişmə: 1751302382.6738274


In [1]:
import math

print("\nRiyazi funksiyalar:")
print("Kvadrat kök:", math.sqrt(16))
print("Sinus:", math.sin(math.pi/2))
print("e üstü:", math.exp(1))
print("Faktorial:", math.factorial(5))
print("GCD (ƏBOB):", math.gcd(48, 18))



Riyazi funksiyalar:
Kvadrat kök: 4.0
Sinus: 1.0
e üstü: 2.718281828459045
Faktorial: 120
GCD (ƏBOB): 6


In [2]:
from datetime import datetime, timedelta

# Hazırkı tarix və vaxt
indiki = datetime.now()
print("\nHazırkı vaxt:", indiki)

# Formatlama
print("Formatlanmış:", indiki.strftime("%d.%m.%Y %H:%M"))

# Tarix əməliyyatları
bir_həftə_sonra = indiki + timedelta(days=7)
print("Bir həftə sonra:", bir_həftə_sonra)


Hazırkı vaxt: 2025-07-01 12:09:28.272560
Formatlanmış: 01.07.2025 12:09
Bir həftə sonra: 2025-07-08 12:09:28.272560


In [3]:
import random

print("\nTəsadüfi ədədlər:")
print("0-1 arası:", random.random())
print("1-10 arası tam:", random.randint(1, 10))
print("Təsadüfi seçim:", random.choice(["alma", "armud", "banan"]))

# Listi qarışdırmaq
list = [1, 2, 3, 4, 5]
random.shuffle(list)
print("Qarışdırılmış list:", list)


Təsadüfi ədədlər:
0-1 arası: 0.9060982721086299
1-10 arası tam: 8
Təsadüfi seçim: banan
Qarışdırılmış list: [5, 3, 2, 1, 4]


In [4]:
import re
mətndəki_rəqəmlər = re.findall(r'\d+', 'Salam 123, Nə var 456?')
print("\nMətndəki rəqəmlər:", mətndəki_rəqəmlər)




Mətndəki rəqəmlər: ['123', '456']


# API İstifadəsi və Web Scraping

In [5]:
import requests

# GET sorğusu nümunəsi
cavab = requests.get('https://api.github.com')
print("Status kod:", cavab.status_code)  # 200 uğurlu deməkdir
print("Məzmun tipi:", cavab.headers['content-type'])
print("JSON məzmunu:", cavab.json())


Status kod: 200
Məzmun tipi: application/json; charset=utf-8
JSON məzmunu: {'current_user_url': 'https://api.github.com/user', 'current_user_authorizations_html_url': 'https://github.com/settings/connections/applications{/client_id}', 'authorizations_url': 'https://api.github.com/authorizations', 'code_search_url': 'https://api.github.com/search/code?q={query}{&page,per_page,sort,order}', 'commit_search_url': 'https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}', 'emails_url': 'https://api.github.com/user/emails', 'emojis_url': 'https://api.github.com/emojis', 'events_url': 'https://api.github.com/events', 'feeds_url': 'https://api.github.com/feeds', 'followers_url': 'https://api.github.com/user/followers', 'following_url': 'https://api.github.com/user/following{/target}', 'gists_url': 'https://api.github.com/gists{/gist_id}', 'hub_url': 'https://api.github.com/hub', 'issue_search_url': 'https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}', 

In [6]:
parametrlər = {'q': 'python', 'page': 1}
github_cavab = requests.get('https://api.github.com/search/repositories', params=parametrlər)
print("\nAxtarış nəticələri:")
print(github_cavab.json()['total_count'], "nəticə tapıldı")


Axtarış nəticələri:
5069125 nəticə tapıldı


In [7]:
url = 'https://httpbin.org/post'
məlumat = {'ad': 'Əli', 'ixtisas': 'İnformatika'}
cavab = requests.post(url, data=məlumat)

print("\nPOST cavabı:")
print(cavab.json())


POST cavabı:
{'args': {}, 'data': '', 'files': {}, 'form': {'ad': 'Əli', 'ixtisas': 'İnformatika'}, 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '36', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.32.4', 'X-Amzn-Trace-Id': 'Root=1-6863b3ea-334dcd2014554b56225bbfb6'}, 'json': None, 'origin': '37.61.116.243', 'url': 'https://httpbin.org/post'}


In [8]:
if github_cavab.status_code == 200:
    nəticələr = github_cavab.json()
    print("\nİlk 3 repo:")
    for repo in nəticələr['items'][:3]:
        print(f"{repo['name']} - {repo['html_url']}")
else:
    print(f"Xəta baş verdi: {github_cavab.status_code}")



İlk 3 repo:
Python - https://github.com/TheAlgorithms/Python
Python - https://github.com/geekcomputers/Python
Python - https://github.com/walter201230/Python


In [9]:
try:
    cavab = requests.get('https://api.github.com/nonexistent', timeout=5)
    cavab.raise_for_status()  # 4XX və 5XX xətaları üçün exception qaldırır
except requests.exceptions.HTTPError as errh:
    print("\nHTTP Xətası:", errh)
except requests.exceptions.ConnectionError as errc:
    print("Bağlantı Xətası:", errc)
except requests.exceptions.Timeout as errt:
    print("Zaman Aşımı:", errt)
except requests.exceptions.RequestException as err:
    print("Nə isə səhv getdi:", err)


HTTP Xətası: 404 Client Error: Not Found for url: https://api.github.com/nonexistent


## 2. Web Scraping

In [15]:
from bs4 import BeautifulSoup
import requests

# Nümunə səhifəni yükləyək
url = 'https://en.wikipedia.org/wiki/Python_(programming_language)'
səhifə = requests.get(url)
soup = BeautifulSoup(səhifə.content, 'html.parser')

# Başlığı çıxaraq
başlıq = soup.find(id='firstHeading')
print("Başlıq:", başlıq.text)

Başlıq: Python (programming language)


In [16]:
print("\nMəzmun başlıqları:")
for başlıq in soup.find_all('span', class_='mw-headline'):
    print(başlıq.text)



Məzmun başlıqları:


In [17]:
print("\nDil versiyaları cədvəli:")
cədvəl = soup.find('table', class_='wikitable')
for sətir in cədvəl.find_all('tr')[1:]:  # İlk sətir başlıqlardır
    sütunlar = sətir.find_all('td')
    if len(sütunlar) >= 2:
        versiya = sütunlar[0].text.strip()
        tarix = sütunlar[1].text.strip()
        print(f"{versiya}: {tarix}")


Dil versiyaları cədvəli:
bool: immutable
bytearray: mutable
bytes: immutable
complex: immutable
dict: mutable
types.EllipsisType: immutable
float: immutable
frozenset: immutable
int: immutable
list: mutable
types.NoneType: immutable
types.NotImplementedType: immutable
range: immutable
set: mutable
str: immutable
tuple: immutable


In [18]:
print("\nXarici linklər:")
for link in soup.find_all('a', href=True):
    url = link['href']
    if url.startswith('http') and 'wikipedia.org' not in url:
        print(f"{link.text.strip()}: {url}")



Xarici linklər:
Edit links: https://www.wikidata.org/wiki/Special:EntityPage/Q28865#sitelinks-wikipedia
Wikimedia Commons: https://commons.wikimedia.org/wiki/Python_(programming_language)
MediaWiki: https://www.mediawiki.org/wiki/Python
Wikibooks: https://en.wikibooks.org/wiki/Python_Programming
Wikifunctions: https://www.wikifunctions.org/wiki/Z610
Wikiquote: https://en.wikiquote.org/wiki/Python
Wikiversity: https://en.wikiversity.org/wiki/Python
Wikidata item: https://www.wikidata.org/wiki/Special:EntityPage/Q28865
python.org: https://www.python.org/
Python Programming: https://en.wikibooks.org/wiki/Python_Programming
"General Python FAQ – Python 3 documentation": https://docs.python.org/3/faq/general.html#what-is-python
"Python 0.9.1 part 01/21": https://www.tuhs.org/Usenet/alt.sources/1991-February/001749.html
Archived: https://web.archive.org/web/20210811171015/https://www.tuhs.org/Usenet/alt.sources/1991-February/001749.html
"Why is Python a dynamic language and also a strongly 

In [19]:
axtarış_url = 'https://en.wikipedia.org/w/index.php'
parametrlər = {
    'search': 'Python programming',
    'title': 'Special:Search',
    'go': 'Go'
}

cavab = requests.get(axtarış_url, params=parametrlər)
soup = BeautifulSoup(cavab.content, 'html.parser')

print("\nAxtarış nəticələri:")
for nəticə in soup.select('.mw-search-result-heading'):
    print(nəticə.get_text())


Axtarış nəticələri:


In [20]:
import time
time.sleep(2)  # 2 saniyə gözlə


def valyuta_məzənnəsi(esas_valyuta='AZN', hədəf_valyuta='USD'):
    try:
        url = f'https://api.exchangerate-api.com/v4/latest/{esas_valyuta}'
        cavab = requests.get(url)
        cavab.raise_for_status()
        məlumat = cavab.json()
        məzənnə = məlumat['rates'][hədəf_valyuta]
        print(f"1 {esas_valyuta} = {məzənnə} {hədəf_valyuta}")
        return məzənnə
    except Exception as e:
        print(f"Xəta baş verdi: {e}")
        return None

print("\nValyuta məzənnələri:")
azn_usd = valyuta_məzənnəsi('AZN', 'USD')
azn_eur = valyuta_məzənnəsi('AZN', 'EUR')



Valyuta məzənnələri:
1 AZN = 0.588 USD
1 AZN = 0.502 EUR


In [24]:
%pip install requests beautifulsoup4


Note: you may need to restart the kernel to use updated packages.


# OOP Əsasları: Siniflər və Obyektlər

In [32]:
class Şəhər:
    """Şəhər haqqında məlumat saxlayan sinif"""
    
    # Sinif dəyişəni (Class Attribute)
    ölkə = "Azərbaycan"
    
    def __init__(self, ad, əhali):
        """Konstruktor metodu - obyekt yaradılanda çağırılır"""
        # İnstans dəyişənləri (Instance Attributes)
        self.ad = ad
        self.əhali = əhali
    
    def təsvir(self):
        """İnstans metodu - obyekt haqqında məlumat qaytarır"""
        return f"{self.ad} şəhəri, {self.ölkə} - Əhali: {self.əhali}"

# Obyekt yaratmaq (instantiation)
bakı = Şəhər("Bakı", 2300000)
gəncə = Şəhər("Gəncə", 350000)

# Obyekt metodlarını çağırmaq
print(bakı.təsvir())
print(gəncə.təsvir())

Bakı şəhəri, Azərbaycan - Əhali: 2300000
Gəncə şəhəri, Azərbaycan - Əhali: 350000


In [33]:
print("\nAtributlara çatma:")
print(f"{bakı.ad} şəhərinin əhalisi: {bakı.əhali}")
print(f"Bütün şəhərlər {Şəhər.ölkə} ölkəsindədir")


Atributlara çatma:
Bakı şəhərinin əhalisi: 2300000
Bütün şəhərlər Azərbaycan ölkəsindədir


In [34]:
class UniversitetŞəhəri(Şəhər):
    """Universitet şəhərləri üçün ixtisaslaşdırılmış sinif"""
    
    def __init__(self, ad, əhali, universitet_sayı):
        # Ata sinfin konstruktorunu çağırmaq
        super().__init__(ad, əhali)
        self.universitet_sayı = universitet_sayı
    
    # Metodun üzərinə yazmaq (Method Overriding)
    def təsvir(self):
        əsas_təsvir = super().təsvir()
        return f"{əsas_təsvir} | Universitet sayı: {self.universitet_sayı}"

# Obyekt yaratmaq
gəncə = UniversitetŞəhəri("Gəncə", 350000, 5)
print("\nİnheritance nümunəsi:")
print(gəncə.təsvir())


İnheritance nümunəsi:
Gəncə şəhəri, Azərbaycan - Əhali: 350000 | Universitet sayı: 5


In [35]:
class Heyvan:
    def səs(self):
        pass

class Pişik(Heyvan):
    def səs(self):
        return "Miyav"

class İt(Heyvan):
    def səs(self):
        return "Hav hav"


In [36]:
print("\nPolymorphism nümunəsi:")
heyvanlar = [Pişik(), İt()]

for heyvan in heyvanlar:
    print(heyvan.səs())


Polymorphism nümunəsi:
Miyav
Hav hav


In [37]:
class Düzbucaqlı:
    """Düzbucaqlı sinfi"""
    
    def __init__(self, en, uzunluq):
        self.en = en
        self.uzunluq = uzunluq
    
    @property
    def sahə(self):
        """Düzbucaqlının sahəsini hesablayır"""
        return self.en * self.uzunluq
    
    @property
    def perimetr(self):
        """Düzbucaqlının perimetrini hesablayır"""
        return 2 * (self.en + self.uzunluq)
    
    @property
    def uzunluq(self):
        """Uzunluq property-si"""
        return self._uzunluq
    
    @uzunluq.setter
    def uzunluq(self, dəyər):
        """Uzunluq üçün setter"""
        if dəyər <= 0:
            raise ValueError("Uzunluq müsbət olmalıdır")
        self._uzunluq = dəyər

# İstifadə
d = Düzbucaqlı(4, 5)
print("\nProperty nümunəsi:")
print("Sahə:", d.sahə)
print("Perimetr:", d.perimetr)


Property nümunəsi:
Sahə: 20
Perimetr: 18


In [38]:
try:
    d.uzunluq = -10  # Xəta verəcək
except ValueError as e:
    print("Xəta:", e)

Xəta: Uzunluq müsbət olmalıdır


In [39]:
def sinif_dekoratoru(cls):
    """Sinifə yeni metod əlavə edən decorator"""
    def yeni_metod(self):
        return f"{self.__class__.__name__} sinfindən salamlar!"
    
    cls.salam_ver = yeni_metod
    return cls

@sinif_dekoratoru
class MənimSinifim:
    """Nümunə sinif"""
    pass

# İstifadə
obj = MənimSinifim()
print("\nSinif decorator nümunəsi:")
print(obj.salam_ver())


Sinif decorator nümunəsi:
MənimSinifim sinfindən salamlar!


## Inheritance (Miras) nümunəsi

In [40]:
class Mühərrik:
    def işə_sal(self):
        return "Mühərrik işə salındı"

class Avtomobil(Mühərrik):
    def sür(self):
        return f"Avtomobil sürülür. {self.işə_sal()}"

# Composition nümunəsi
class Avtomobil:
    def __init__(self):
        self.mühərrik = Mühərrik()
    
    def sür(self):
        return f"Avtomobil sürülür. {self.mühərrik.işə_sal()}"

print("\nInheritance vs Composition:")
avto1 = Avtomobil()
print(avto1.sür())


Inheritance vs Composition:
Avtomobil sürülür. Mühərrik işə salındı


## 2.5 Abstract Base Classes (ABC)

In [41]:
from abc import ABC, abstractmethod

class Şəkil(ABC):
    @abstractmethod
    def sahə(self):
        pass
    
    @abstractmethod
    def perimetr(self):
        pass

class Düzbucaqlı(Şəkil):
    def __init__(self, en, uzunluq):
        self.en = en
        self.uzunluq = uzunluq
    
    def sahə(self):
        return self.en * self.uzunluq
    
    def perimetr(self):
        return 2 * (self.en + self.uzunluq)

In [42]:
try:
    ş = Şəkil()
except TypeError as e:
    print("\nAbstract sinif nümunəsi:")
    print("Xəta:", e)

d = Düzbucaqlı(4, 5)
print("Düzbucaqlı sahə:", d.sahə())


Abstract sinif nümunəsi:
Xəta: Can't instantiate abstract class Şəkil without an implementation for abstract methods 'perimetr', 'sahə'
Düzbucaqlı sahə: 20
